### ISSUE TITLE
binance-bot crashes very often because of a LockError

### ISSUE THREAD

**Issue by kafumichels** [chrisleekr/binance-trading-bot#417] opened 2022-03-01 20:07 UTC
## Version

Running Version:
v0.0.85
(55d7027)

## Description

binance-bot crashes randomly. This message appears in frontend:

<img width="505" alt="Screenshot 2022-03-01 at 20 39 22" src="https://user-images.githubusercontent.com/100723931/156237249-d74b3cdb-7129-446e-97dd-63cf5a5982fd.png">

docker ps shows that binance-bot was restarted
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/100723931/156237746-9008a014-0f47-44ca-9703-5316820051a0.png">

Logs like this can be found after crash:

docker logs binance-bot --tail=10000 > error.log
(node:47) UnhandledPromiseRejectionWarning: LockError: Unable to fully release the lock on resource "redlock:trailing-trade-symbols:EOSUSDT-processed-data".
    at loop (/srv/node_modules/redlock/redlock.js:282:18)
    at /srv/node_modules/redlock/redlock.js:462:10
    at tryCatcher (/srv/node_modules/standard-as-callback/built/utils.js:12:23)
    at /srv/node_modules/standard-as-callback/built/index.js:22:53
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

docker logs binance-bot --tail=10000 > error.log
(node:47) UnhandledPromiseRejectionWarning: LockError: Unable to fully release the lock on resource "redlock:trailing-trade-symbols:SUSHIUSDT-latest-candle".
    at loop (/srv/node_modules/redlock/redlock.js:282:18)
    at /srv/node_modules/redlock/redlock.js:462:10
    at tryCatcher (/srv/node_modules/standard-as-callback/built/utils.js:12:23)
    at /srv/node_modules/standard-as-callback/built/index.js:22:53
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 52)`

Sometimes last buy price is not updated, or selled symbols does not appear in the statistics. I think this is related to the restarts.

## To Reproduce

1. Open the frontend and wait till the disconnect message appears
2. Check the logs of binace-bot docker logs binance-bot --tail=10000 > error.log

## Expected Behaviours

Binance-bot runs stable.

## Additional context

The bot is running since september, and was updated several times.
And since september with image mongo:3.6.23 on a raspberry pi 4 Model B 8gb, Ubuntu 21.04
docker-compose.rpi.yml was used to setup. I changed the mongo db image. This change was done, because I tried to fix the mongodb image issue with the docker-compose.server.yml on raspberry pi by my own, before I saw that this was already fixed in the rpi yml. But bot was already running with my fix and I didn't wand to change the database and reset everything.
Maybe it's related to the mongo db image. But it was working fine for 4-5 month. If you think its related to this change, I'm fine if you just drop me a message and close the bug :-)

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/100723931/156239198-0af943f0-e8cf-4d47-af34-834742c85db1.png">

**Comment by Yuxanju** [comment] 2022-03-01 23:47
You have to make sure your wallet is synchronize and then debug with bech13 And then you compile the contract to binance

**Comment by zoolle** [comment] 2022-06-22 13:17
@kafumichels its happening the same for me and I just started it yesterday. I get something in regards with this `LockError: Exceeded 1 attempts to lock the resource "redlock:auth-jwt-secret".`

**Comment by chrisleekr** [comment] 2022-07-22 14:05
Hi @kafumichels 

Sorry for the late reply.

> mongo:3.6.23 on a raspberry pi 4 Model B 8gb, Ubuntu 21.04

I didn't test the bot with Ubuntu, I tested with Raspberry Pi OS 32bit. 
So I cannot guarantee it's working or not in your environment.

> (node:47) UnhandledPromiseRejectionWarning: LockError: Unable to fully release the lock on resource "redlock:trailing-trade-symbols:EOSUSDT-processed-data".

There is a code to ignore the redlock error exception. Not sure why it's crashing it. 
I feel like there is something else going on with your setup.

I am sorry I couldn't help more.
As the issue is very old, I will close it for now. Please open a new issue if the issue persists.

**Closed by chrisleekr** 2022-07-22 14:05 UTC
Labels: bug
