### ISSUE TITLE
Not fully selling the coin.

### ISSUE THREAD

**Issue by volter50000** [chrisleekr/binance-trading-bot#361] opened 2021-10-15 12:10 UTC
Hi. Faced an interesting problem. Previous versions did not have this problem.
The bot does not fully sell coins.
For example, the Bot bought THETA / USDT in the amount of 2.5 theta.
Then the sell trigger went off.
But the bot only sold 2.3 theta.
The purchase price was dropped and the remaining 0.2 theta remained unsold.
This happens on all coins. Somewhere more, somewhere less. Here are screenshots. Is it possible to fix this?
![image](https://user-images.githubusercontent.com/36567578/137484392-58870401-7626-4e8e-bc99-0cfedda795be.png)
![image](https://user-images.githubusercontent.com/36567578/137484472-d8f80828-f628-4054-a387-8e1cae9400d0.png)

**Comment by ilbuonmarcio** [comment] 2021-10-15 12:16
As previously answered on other now closed Issues, the bot tries to sell all available coins, but there is no guarantee that it will be bought 100% every time, more often it will result in some dust coins remaining in your wallet.

The statistics about trades you're viewing aren't representative of your actual gain, but if you have a look at how much asset in USD/EUR you have in your Binance App or on the website you can see that you have gained value from the trade and the whole wallet value increased.

Always check the App or website for exact value gains and lows.

We will try and come up with a solution to this problem, until then, if your question has been answered please close this issue, thanks!

**Comment by volter50000** [comment] 2021-10-15 13:04
Yes, it's really weird. I looked at previous versions and there is no difference.
I understand that everything will be correct on the exchange website.
I didn't quite understand with the commission and 0.1%. The commission is paid upon closing in USDT, that is, we sold the position by 100%, and paid a commission from the USDT received.
USDT -> THETA (Commission is charged in THETA after purchase).
THETA -> USDT (commission charged in USDT after sale).
Maybe I'm wrong = \

**Comment by ilbuonmarcio** [comment] 2021-10-17 00:27
You should consider commissions included, both for buy and sell, while you're configuring the bot.

If the issue is resolved please mark it as closed, thanks!

**Closed** 2021-10-17 01:18 UTC
Labels: bug
