### ISSUE TITLE
Current price stops updating (similar to issue #179)

### ISSUE THREAD

**Issue by drowsygoat** [chrisleekr/binance-trading-bot#423] opened 2022-05-03 11:56 UTC
Current price freezes and when I look at the logs by clicking on the clock icon, it shows that the log is empty. On the frontend, when I close the trading pair monitor ((x) icon) the trading pair panel does not reappear automatically (as would be expected for a pair that is actively monitoring), but when I reactivate the pair in the global options, the function resumes (i.e. the price is being updated and the the entries in the log are present again). 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/32292322/166447092-eaea8ffc-a74c-43e5-ac3c-693db3011a70.png">

This may be a possible bug, or maybe some limitation due to the docker container configuration which I'm not aware of.
Version v0.0.85 (55d7027). Docker hub image used, live mode. Docker v. 4.6.1 running on Mac OS).

Run with:
`docker-compose -f docker-compose.server.yml up -d`

**Comment by eppenga** [comment] 2022-05-08 20:12
Had the same and I am now restarting it via a cron job every hour, please see: https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#setup-cronjob-or-scheduled-task-to-restart-the-bot-periodically

Strange thing is, that in my case the current prize only froze for one coin, the rest functioned perfectly.

**Comment by eppenga** [comment] 2022-05-08 20:13
Not sure if I remember correctly, but I thought I also had the issue with LUNABUSD...

**Comment by hugoleosp** [comment] 2022-05-13 22:52
I used to have this problem when I had low memory, even setting to use more virtual memory, the bot would experience lag (sometimes just adding new coins, sometimes updating).. I switched to Alpine and gave more memory to the virtual machine... It really didn't solve 100%, but from a needed restart every few hours, it's now days.. I'm not an expert with Linux, just basic knowledge.. But it seemed the best solution so far for me.

**Comment by chrisleekr** [comment] 2022-07-22 13:54
Sorry for the late reply.

With the latest release v0.0.86, it will start using WebSocket to get candles, which will use fewer API calls. 
(Thanks to @habibalkhabbaz)
Please try the latest version and see whether the problem persists.

As the issue is old, I will close it for now.

**Closed by chrisleekr** 2022-07-22 13:54 UTC
Labels: bug
