### ISSUE TITLE
Looks like sometimes the bot doesn't seem to be selling the full amount.

### ISSUE THREAD

**Issue by peweb** [chrisleekr/binance-trading-bot#532] opened 2022-10-25 18:28 UTC
Looks like sometimes the bot doesn't seem to be selling the full amount so trade at a loss.

![image](https://user-images.githubusercontent.com/36623351/198828514-9cc83dd7-92e7-47fa-8669-817c28a3073a.png)

![image](https://user-images.githubusercontent.com/36623351/198827902-d3ad0beb-2937-469b-9990-8a559fec4d55.png)

Bought 97 XRP and sold 96. There is 1+ remining balance. 

When the bot is going to sell this balance and at what price?

This is the log:

(23:33:01.747) XRPUSDT BUY Grid Trade #1 Order Filled: STOP_LOSS_LIMIT
- Order Result:
{
  "symbol": "XRPUSDT",
  "orderId": 4811896499,
  "orderListId": -1,
  "clientOrderId": "1j8xq7Jxz2C9kKjnl7SJsU",
  "transactTime": 1666999981087,
  "currentGridTradeIndex": 0,
  "status": "FILLED",
  "type": "STOP_LOSS_LIMIT",
  "side": "BUY",
  "stopPrice": "0.47360000",
  "price": "0.47370000",
  "origQty": "42.00000000",
  "cummulativeQuoteQty": "19.89120000",
  "executedQty": "42.00000000",
  "isWorking": false,
  "updateTime": 1666999981087
}

(00:58:20.954) XRPUSDT BUY Grid Trade #2 Order Filled: STOP_LOSS_LIMIT
- Order Result:
{
  "symbol": "XRPUSDT",
  "orderId": 4812004887,
  "orderListId": -1,
  "clientOrderId": "Ns97WbMgkzQi7gQaMlblyS",
  "transactTime": 1667005100225,
  "currentGridTradeIndex": 1,
  "status": "FILLED",
  "type": "STOP_LOSS_LIMIT",
  "side": "BUY",
  "stopPrice": "0.47250000",
  "price": "0.47260000",
  "origQty": "55.00000000",
  "cummulativeQuoteQty": "25.98750000",
  "executedQty": "55.00000000",
  "isWorking": false,
  "updateTime": 1667005100243
}

(08:26:10.204) XRPUSDT Sell Action Grid Trade #1: STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "XRPUSDT",
  "side": "sell",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 96,
  "stopPrice": 0.4763,
  "price": 0.4762,
  "timeInForce": "GTC"
}

Traling ...

(08:26:51.361) XRPUSDT Sell Action Grid Trade #1: STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "XRPUSDT",
  "side": "sell",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 96,
  "stopPrice": 0.4771,
  "price": 0.477,
  "timeInForce": "GTC"
}

(08:26:55.781) XRPUSDT SELL Grid Trade #1 Order Filled: STOP_LOSS_LIMIT
- Order Result:
{
  "symbol": "XRPUSDT",
  "orderId": 4812474904,
  "orderListId": -1,
  "clientOrderId": "wqtKByD0XqsYlTzuvw38Hg",
  "transactTime": 1667032014320,
  "currentGridTradeIndex": 0,
  "status": "FILLED",
  "type": "STOP_LOSS_LIMIT",
  "side": "SELL",
  "stopPrice": "0.47710000",
  "price": "0.47700000",
  "origQty": "96.00000000",
  "cummulativeQuoteQty": "45.80160000",
  "executedQty": "96.00000000",
  "isWorking": false,
  "updateTime": 1667032014495
}

(08:26:56.066) XRPUSDT Action - Removed last buy price:
- Message: All sell orders are executed. Delete last buy price.
{
  "lastBuyPrice": 0.47297628865979385,
  "currentPrice": 0.4772,
  "minNotional": "10.00000000",
  "openOrders": []
}

(08:26:56.084) XRPUSDT Loss:
 - Profit: -0.0771000000000015
 - ProfitPercentage: -0.16805184105042537
 - Total Buy Amount: 45.8787
 - Total Sell Amount: 45.8016

**Comment by peweb** [comment] 2022-10-29 11:13
Looks like sometimes the bot doesn't seem to be selling the full amount.

![image](https://user-images.githubusercontent.com/36623351/198827902-d3ad0beb-2937-469b-9990-8a559fec4d55.png)

Bought 97 XRP and sold 96. There is 1+ remining balance. 

When the bot is going to sell this balance and at what price?

This is the log:

(23:33:01.747) XRPUSDT BUY Grid Trade #1 Order Filled: STOP_LOSS_LIMIT
- Order Result:
{
  "symbol": "XRPUSDT",
  "orderId": 4811896499,
  "orderListId": -1,
  "clientOrderId": "1j8xq7Jxz2C9kKjnl7SJsU",
  "transactTime": 1666999981087,
  "currentGridTradeIndex": 0,
  "status": "FILLED",
  "type": "STOP_LOSS_LIMIT",
  "side": "BUY",
  "stopPrice": "0.47360000",
  "price": "0.47370000",
  "origQty": "42.00000000",
  "cummulativeQuoteQty": "19.89120000",
  "executedQty": "42.00000000",
  "isWorking": false,
  "updateTime": 1666999981087
}

(00:58:20.954) XRPUSDT BUY Grid Trade #2 Order Filled: STOP_LOSS_LIMIT
- Order Result:
{
  "symbol": "XRPUSDT",
  "orderId": 4812004887,
  "orderListId": -1,
  "clientOrderId": "Ns97WbMgkzQi7gQaMlblyS",
  "transactTime": 1667005100225,
  "currentGridTradeIndex": 1,
  "status": "FILLED",
  "type": "STOP_LOSS_LIMIT",
  "side": "BUY",
  "stopPrice": "0.47250000",
  "price": "0.47260000",
  "origQty": "55.00000000",
  "cummulativeQuoteQty": "25.98750000",
  "executedQty": "55.00000000",
  "isWorking": false,
  "updateTime": 1667005100243
}

(08:26:10.204) XRPUSDT Sell Action Grid Trade #1: STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "XRPUSDT",
  "side": "sell",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 96,
  "stopPrice": 0.4763,
  "price": 0.4762,
  "timeInForce": "GTC"
}

Traling ...

(08:26:51.361) XRPUSDT Sell Action Grid Trade #1: STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "XRPUSDT",
  "side": "sell",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 96,
  "stopPrice": 0.4771,
  "price": 0.477,
  "timeInForce": "GTC"
}

(08:26:55.781) XRPUSDT SELL Grid Trade #1 Order Filled: STOP_LOSS_LIMIT
- Order Result:
{
  "symbol": "XRPUSDT",
  "orderId": 4812474904,
  "orderListId": -1,
  "clientOrderId": "wqtKByD0XqsYlTzuvw38Hg",
  "transactTime": 1667032014320,
  "currentGridTradeIndex": 0,
  "status": "FILLED",
  "type": "STOP_LOSS_LIMIT",
  "side": "SELL",
  "stopPrice": "0.47710000",
  "price": "0.47700000",
  "origQty": "96.00000000",
  "cummulativeQuoteQty": "45.80160000",
  "executedQty": "96.00000000",
  "isWorking": false,
  "updateTime": 1667032014495
}

(08:26:56.066) XRPUSDT Action - Removed last buy price:
- Message: All sell orders are executed. Delete last buy price.
{
  "lastBuyPrice": 0.47297628865979385,
  "currentPrice": 0.4772,
  "minNotional": "10.00000000",
  "openOrders": []
}

(08:26:56.084) XRPUSDT Loss:
 - Profit: -0.0771000000000015
 - ProfitPercentage: -0.16805184105042537
 - Total Buy Amount: 45.8787
 - Total Sell Amount: 45.8016

**Comment by peweb** [comment] 2022-10-29 12:45
The next trade

![image](https://user-images.githubusercontent.com/36623351/198832186-33a70790-1185-484d-bce2-8fca967f22d7.png)

Bot didnt sell that 1 XRP left from the previous trade.

Grid sell is set up to sell 100%

**Comment by peweb** [comment] 2022-10-29 17:14
Happened again with another pair:

![image](https://user-images.githubusercontent.com/36623351/198844246-0188a4ed-09f1-4fbc-8ba3-9a14f419b7b7.png)

![image](https://user-images.githubusercontent.com/36623351/198844258-2d2cbb47-75f5-43bb-8d6d-01f725732411.png)

Bot doesnt sell all amount.

Bought 1,107 XLM 
Sold 1,103 XLM

Is this a bug? Why bot cant sell all amount?

**Comment by DecisiveDesignDE** [comment] 2022-11-03 17:57
I can confirm this behaviour, it's especially noticable with higher buys.
Had the bot buy BAT for 20k+ and it reached the trigger price of 0.1% profit. 
The bot sold most of it, but in the "closed trades" marked it as a $11 loss when in actuality I still had $21 left over, so it was a $10 profit.

**Comment by chrisleekr** [comment] 2022-11-04 10:51
@peweb 

It's designed, not a bug. 

It calculates 10% from quantity for commission. It does not use BNB commission even if you choose to use it.
Here is the code - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/place-sell-order.js#L106

Even if you try to sell from the Binance app, I found it leaves small amounts.

Please close the issue if it's answered.

**Comment by peweb** [comment] 2022-11-04 12:08
@chrisleekr 

10%?

https://www.binance.com/en/fee/schedule

For a Regular User it should be 0.1000% / 0.1000%

**Comment by chrisleekr** [comment] 2022-11-04 12:24
Ah sorry, typo. It's 0.1%. See the code - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/place-sell-order.js#L106

Yes, export logs should work. Check console/network tab whether you got an error or not.

**Comment by peweb** [comment] 2022-11-04 13:16
@chrisleekr
 
![image](https://user-images.githubusercontent.com/36623351/199981457-2f7227b8-8081-491c-a5c1-c1bbde8c0043.png)

**Comment by chrisleekr** [comment] 2022-11-04 13:19
Ah, it looks like the logs are too big. That is a bug. 
Could you open a new issue with this bug? I will fix it up when I get time.

**Closed** 2022-11-30 19:14 UTC
Labels: question
