### ISSUE TITLE
Still Place order when current price is over ATH

### ISSUE THREAD

**Issue by thanhtran72085** [chrisleekr/binance-trading-bot#271] opened 2021-08-14 09:35 UTC
Hi Chrisleekr,
i have an issue with ATH when current price is over ATH restricted price, the bot is still place buy order. how to do resolve ?
![2021-08-14_16-29](https://user-images.githubusercontent.com/59467389/129441652-b31ea57a-5775-436a-9cba-111a8fed6738.png)

**Comment by chrisleekr** [comment] 2021-08-14 11:46
Did you enable auto trigger buy?
![image](https://user-images.githubusercontent.com/5715919/129445282-5d6a44a0-75bf-404c-863f-6a4fa9dbb9c4.png)

**Comment by azorpax** [comment] 2021-08-14 16:56
> Did you enable auto trigger buy?
> ![image](https://user-images.githubusercontent.com/5715919/129445282-5d6a44a0-75bf-404c-863f-6a4fa9dbb9c4.png)

would it will be better if there is an option to still check the ATH restriction before executing this feature?

**Comment by chrisleekr** [comment] 2021-08-15 02:21
@azorpax Well, that defeats the purpose of auto-trigger buy. The purpose of auto-trigger buy is to purchase the coin for following the rise.

**Comment by azorpax** [comment] 2021-08-15 06:26
> @azorpax Well, that defeats the purpose of auto-trigger buy. The purpose of auto-trigger buy is to purchase the coin for following the rise.
yes i get that. i think the auto trigger will still be beneficial because it will still be triggered without the need of hitting the buy trigger price. its just the ATH price that i think we should have an option to avoid. Lets just resched the auto trigger timer if it wasnt able to trigger because of the ATH restriction.

**Comment by chrisleekr** [comment] 2021-08-15 09:22
@azorpax Right, so rescheduling auto-buy trigger until it's under the ATH. Sounds like enhancement rather than a bug. Let me put it in the TODO list.

@thanhtran72085 Could you please confirm you enabled the auto-buy trigger? If yes, you can close the issue because that is not a bug.

**Comment by thanhtran72085** [comment] 2021-08-15 16:26
> Did you enable auto trigger buy?
> ![image](https://user-images.githubusercontent.com/5715919/129445282-5d6a44a0-75bf-404c-863f-6a4fa9dbb9c4.png)

I confirm, i don't enable this function, i saw many this issue.

**Comment by chrisleekr** [comment] 2021-08-15 22:33
@thanhtran72085 

Again, please follow the bug template. You will need to provide more information to find out what happened.
I cannot tell what is going on with just one screenshot.

Are you saying, you didn't enable the auto-trigger buy, but the bot automatically purchase?

What are your settings? Can you provide a setting?

Have you set up Slack? What messages did you receive in Slack?

Have you tried to see the log?

**Comment by thanhtran72085** [comment] 2021-08-16 06:53
Hi Chrisleekr,
In fact, I never enable "auto-trigger buying", bad news as i don't screenshot the setting at that time, i have Slack logging, can you see them as bellow:
![2021-08-16_135025](https://user-images.githubusercontent.com/59467389/129522979-25186842-4ac8-4f07-b12f-0b07c5c179e3.png)

**Comment by chrisleekr** [comment] 2021-08-16 22:39
@thanhtran72085 

Are you still experiencing the bot is automatically placing an order without enabling "Auto trigger buy"?

**Comment by thanhtran72085** [comment] 2021-08-17 03:30
> @thanhtran72085
> 
> Are you still experiencing the bot is automatically placing an order without enabling "Auto trigger buy"?

**Comment by thanhtran72085** [comment] 2021-08-17 03:32
> > @thanhtran72085
> > Are you still experiencing the bot is automatically placing an order without enabling "Auto trigger buy"?

I don't see this issue again, now, if i see it again, i will screenshot and send you slack logging.

**Comment by chrisleekr** [comment] 2021-08-17 10:57
Ok. Please close the issue and re-open it when it happens.

**Closed** 2021-08-17 14:39 UTC
Labels: bug
