### ISSUE TITLE
errno EHOSTUNREACH when building

### ISSUE THREAD

**Issue by fsabiu** [chrisleekr/binance-trading-bot#101] opened 2021-04-16 15:56 UTC
## Description
Hi all,
I am following the guide on my Raspberry Pi, but when executing
`docker-compose up -d`
or
`docker build . --build-arg NODE_ENV=production --target production-stage -t chrisleekr/binance-trading-bot:latest`

I get the following error during the step 5 of 7, namely RUN npm install:
`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!`
`npm ERR! code EHOSTUNREACH`
`npm ERR! errno EHOSTUNREACH`
`npm ERR! request to https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.12.11.tgz failed, reason: connect EHOSTUNREACH 104.16.23.35:443`

Do you know this error?

Thanks
fsabiu

**Comment by chrisleekr** [comment] 2021-04-16 21:59
This is not a bug.

 Please google the error code and find a solution.

**Comment by chrisleekr** [comment] 2021-04-18 04:15
Please close the issue if you found a solution.

**Closed** 2021-04-19 13:14 UTC
Labels: bug
