### ISSUE TITLE
Price Filter tickSize problem on creating an order

### ISSUE THREAD

**Issue by caebwallace** [chrisleekr/binance-trading-bot#284] opened 2021-08-26 13:24 UTC
## Version

v0.0.76 (9119c6d)

## Description

As the ticksize in 0.1 and the create order use 2 decimals, there is a 'PRICE_FILTER' error.
https://api.binance.com/api/v3/exchangeInfo?symbol=AAVEUSDT

```
AAVEUSDT Buy Action Grid Trade #1 (12:10:50.056): STOP_LOSS_LIMIT
- Order Params: 
{
  "orderParams": {
    "symbol": "AAVEUSDT",
    "side": "buy",
    "type": "STOP_LOSS_LIMIT",
    "quantity": 1.3895,
    "stopPrice": 359.14,
    "price": 359.49,
    "timeInForce": "GTC"
  }
}
```

```
Execution failed (12:10:50.789)
Job: Trailing Trade
Code: -1013
Message:
Filter failure: PRICE_FILTER
- Current API Usage: 366
```

## To Reproduce

Place a manual limit BUY order to AAVEUSDT with a 2 decimals price.

**Comment by chrisleekr** [comment] 2021-08-28 03:51
I assume the issue is resolved. I will close the issue.

**Closed by chrisleekr** 2021-08-28 03:51 UTC
Labels: bug

**Comment by caebwallace** [comment] 2021-08-28 10:26
Yep, will test that this afternoon !

**Comment by caebwallace** [comment] 2021-08-28 22:02
To confirm you that v0.0.77 fix that issue on `Apply to global only`
=> perhaps we could add a cronjob that runs every 6 hours, cleans redis `trailing-trade-symbols.symbol-info` and refresh exchangeInfos for all selected symbols ?
