### ISSUE TITLE
Fetching error ETIMEDOUT on buy order

### ISSUE THREAD

**Issue by Suniron** [chrisleekr/binance-trading-bot#249] opened 2021-07-24 15:35 UTC
Hey there,

I have a fresh deployment of this bot on my Rapseberry Pi 4 with Raspbian 64 Bits since midday.

After few hours of running, the bot detect the first opportunity to put a buy order! 
But... it fail again and again..

The error which is showed is theese:

```
Execution failed (14:57:53.113)


Job: Trailing Trade Indicator
Code: ETIMEDOUT
Message:

request to https://api.binance.com/api/v3/openOrders?symbol=XRPBUSD&recvWindow=10000&timestamp=1627138543894&signature=595c4714b0c9ed72989ef823e0a1aea5a4b64f355eef27131b failed, reason: connect ETIMEDOUT 52.222.192.131:443Stack:FetchError: request to https://api.binance.com/api/v3/openOrders?symbol=XRPBUSD&recvWindow=10000&timestamp=1627138543894&signature=595714b0c9e9ef823e0a1aea5a4b64f355eef27131b2e failed, reason: connect ETIMEDOUT 52.222.192.131:443


   at ClientRequest.<anonymous> (/srv/node_modules/node-fetch/index.js:133:11)
   at ClientRequest.emit (events.js:375:28)
   at TLSSocket.socketErrorListener (_http_client.js:475:9)
   at TLSSocket.emit (events.js:375:28)
   at emitErrorNT (internal/streams/destroy.js:106:8)
   at emitErrorCloseNT (internal/streams/destroy.js:74:3)
   at processTicksAndRejections (internal/process/task_queues.js:82:21)

- Current API Usage: 228
```

(I just mofidied the signature to give the error here 😉).

An idea?

**Comment by Suniron** [comment] 2021-07-25 03:56
I see that the date in the message is not the same of the system.

It's shifted by 2 hours (I'm in France where it is GMT+2).

I had checked the date on the 3 docker image and it's the same, see bellow:

![Screenshot_20210725_005907_com.server.auditor.ssh.client.png](https://user-images.githubusercontent.com/36677774/126887192-8e14b922-4b73-40eb-a076-f41e041e5df6.png)

But in slack bot message the date is shifted:

![Screenshot_20210724_235414_com.Slack.png](https://user-images.githubusercontent.com/36677774/126887203-597187b7-69a1-4985-8ab9-1fc638ef3acb.png)

**Comment by chrisleekr** [comment] 2021-07-25 07:08
First of all, this is not a bug of the bot.

Secondly, there are already closed issues related to ETIMEDOUT. 
Please search first before you submit the issue.

Please close the issue if your issue is duplicated.

**Comment by Suniron** [comment] 2021-07-25 08:56
Of course, I had consulted the other issues but the cause does not seem to be the same: it seems that there is a problem with the time of the request made to the API.

**Comment by chrisleekr** [comment] 2021-07-25 11:50
Hi @Suniron 

The error is caused due to timeout between your bot and Binance API.
It's most likely caused by your RPi has a slow network.
If you are using WiFi, try ethernet.

**Comment by Suniron** [comment] 2021-07-25 12:30
Thanks for your answer @chrisleekr. 

I'm already connected over ethernet 😔. 

It's strange that the time in parenthesis, after the message `Execution failed` is not the same as the system / the docker image. 

Is it just a log problem with this time error? 

.. Because, I think, if the requests was sent with a bad time, the binance api server block them.

**Comment by chrisleekr** [comment] 2021-07-25 12:32
@Suniron 

Yeah, the error does not stop the bot from working. I mean, eventually, the request will go through and process the request.
But those error messages would be so annoying to receive.

I suggest trying with Cloud if you don't have any other option.

**Comment by Suniron** [comment] 2021-07-25 12:44
@chrisleekr

Mmmh effectively, I just see that 3 order are opened this morning like that:

![Screenshot_20210725_144059.jpg](https://user-images.githubusercontent.com/36677774/126899352-a59fd1a7-23ca-43f3-a99d-af16330277fd.jpg)

But all other open order who got the **ETIMEDOUT ERROR** are failed ant don't appear in the Binance interface.

I think that the probleme isn't far, link a date sync problem.

**Comment by chrisleekr** [comment] 2021-07-26 11:45
Ok, please close the issue if your issue is resolved.

**Comment by Suniron** [comment] 2021-07-26 11:48
> Ok, please close the issue if your issue is resolved.
> 

It's not solved, I use a fork we're I haven't the problem :(

**Closed** 2021-07-26 11:48 UTC
Labels: bug

**Comment by Zaabure** [comment] 2021-12-30 02:37
@Suniron Which fork do you use? I have the same issue, checked all others, tried DNS change, sitting on 1000 MB/S optical, but it's still not working..
