### ISSUE TITLE
BOT STUCK ON FRONTEND LOADING

### ISSUE THREAD

**Issue by doyouknow93** [chrisleekr/binance-trading-bot#115] opened 2021-04-25 22:47 UTC
## Description

Hi guys, i can't access on bot frontend because stuck at loading.

![Schermata da 2021-04-26 00-29-23](https://user-images.githubusercontent.com/83189401/116012009-3b604680-a628-11eb-9353-814fe10f5f43.png)

This is my docker-compose.yml

![Schermata da 2021-04-26 00-42-51](https://user-images.githubusercontent.com/83189401/116012054-85492c80-a628-11eb-8103-1a35fcf7c494.png)

This is my .env

![Schermata da 2021-04-26 00-43-37](https://user-images.githubusercontent.com/83189401/116012134-fdafed80-a628-11eb-84d2-8a3615c2edc1.png)

Thanks ^_^

**Comment by Copane40** [comment] 2021-04-26 03:24
Wow !! Good work guys ...hope I got the bug out

**Comment by chrisleekr** [comment] 2021-04-26 09:34
Please check the log - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

**Comment by benfl3713** [comment] 2021-04-26 16:08
I had this issue today, and switched the `BINANCE_MODE` variable in the docker-compose file to be `live` instead of `test`. Then after doing a `docker-compose down` and `docker-compose up -d` again, it actually loaded some data on the frontend

**Comment by chrisleekr** [comment] 2021-04-27 22:14
Please close the issue if the issue is resolved.

**Comment by doyouknow93** [comment] 2021-04-27 23:05
Hi @chrisleekr i've the log.

This is my output:

`at dispatchRequest (/srv/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1086)
(node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at dispatchHttpRequest (/srv/node_modules/axios/lib/adapters/http.js:109:74)
    at new Promise (<anonymous>)
    at httpAdapter (/srv/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/srv/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1089)
(node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at dispatchHttpRequest (/srv/node_modules/axios/lib/adapters/http.js:109:74)
    at new Promise (<anonymous>)
    at httpAdapter (/srv/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/srv/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1092)
[2021-04-27T23:03:03.996Z]  INFO: binance-api/25 on 9612d846b41b: received (version=0.0.65, server=websocket, message={"command":"latest","data":{}})
[2021-04-27T23:03:03.997Z]  INFO: binance-api/25 on 9612d846b41b: cached values (version=0.0.65, server=websocket)
    payload: {
      "command": "latest",
      "data": {}
    }
    --
    cacheTrailingTradeCommon: {
      "last-symbol": "ETHUSDT",
      "exchange-symbols": "[\"BNBUSDT\",\"BTCUSDT\",\"ETHUSDT\",\"LTCUSDT\",\"TRXUSDT\",\"XRPUSDT\"]"
    }
    --
    cacheTrailingTradeSymbols: {
      "BTCUSDT-symbol-info": "{\"symbol\":\"BTCUSDT\",\"status\":\"TRADING\",\"baseAsset\":\"BTC\",\"baseAssetPrecision\":8,\"quoteAsset\":\"USDT\",\"quotePrecision\":8,\"filterLotSize\":{\"filterType\":\"LOT_SIZE\",\"minQty\":\"0.00000100\",\"maxQty\":\"900.00000000\",\"stepSize\":\"0.00000100\"},\"filterPrice\":{\"filterType\":\"PRICE_FILTER\",\"minPrice\":\"0.01000000\",\"maxPrice\":\"1000000.00000000\",\"tickSize\":\"0.01000000\"},\"filterMinNotional\":{\"filterType\":\"MIN_NOTIONAL\",\"minNotional\":\"10.00000000\",\"applyToMarket\":true,\"avgPriceMins\":5}}",
      "BNBUSDT-symbol-info": "{\"symbol\":\"BNBUSDT\",\"status\":\"TRADING\",\"baseAsset\":\"BNB\",\"baseAssetPrecision\":8,\"quoteAsset\":\"USDT\",\"quotePrecision\":8,\"filterLotSize\":{\"filterType\":\"LOT_SIZE\",\"minQty\":\"0.01000000\",\"maxQty\":\"9000.00000000\",\"stepSize\":\"0.01000000\"},\"filterPrice\":{\"filterType\":\"PRICE_FILTER\",\"minPrice\":\"0.00010000\",\"maxPrice\":\"10000.00000000\",\"tickSize\":\"0.00010000\"},\"filterMinNotional\":{\"filterType\":\"MIN_NOTIONAL\",\"minNotional\":\"10.00000000\",\"applyToMarket\":true,\"avgPriceMins\":5}}",
      "ETHUSDT-symbol-info": "{\"symbol\":\"ETHUSDT\",\"status\":\"TRADING\",\"baseAsset\":\"ETH\",\"baseAssetPrecision\":8,\"quoteAsset\":\"USDT\",\"quotePrecision\":8,\"filterLotSize\":{\"filterType\":\"LOT_SIZE\",\"minQty\":\"0.00001000\",\"maxQty\":\"9000.00000000\",\"stepSize\":\"0.00001000\"},\"filterPrice\":{\"filterType\":\"PRICE_FILTER\",\"minPrice\":\"0.01000000\",\"maxPrice\":\"100000.00000000\",\"tickSize\":\"0.01000000\"},\"filterMinNotional\":{\"filterType\":\"MIN_NOTIONAL\",\"minNotional\":\"10.00000000\",\"applyToMarket\":true,\"avgPriceMins\":5}}"
    }
[2021-04-27T23:03:03.998Z]  INFO: binance-api/25 on 9612d846b41b: Finding document from MongoDB (version=0.0.65, server=websocket, helper=mongo, funcName=findOne, collectionName=trailing-trade-common)
    payload: {
      "command": "latest",
      "data": {}
    }
    --
    query: {
      "key": "configuration"
    }
[2021-04-27T23:03:04.000Z]  INFO: binance-api/25 on 9612d846b41b: Found document from MongoDB (version=0.0.65, server=websocket, helper=mongo, funcName=findOne)
    payload: {
      "command": "latest",
      "data": {}
    }
    --
    result: {
      "_id": "6085e70294e5eefa25b715e1",
      "key": "configuration",
      "enabled": true,
      "cronTime": "* * * * * *",
      "symbols": [
        "BTCUSDT",
        "ETHUSDT",
        "BNBUSDT"
      ],
      "supportFIATs": [
        "USDT"
      ],
      "candles": {
        "interval": "1h",
        "limit": 100
      },
      "buy": {
        "enabled": true,
        "maxPurchaseAmount": 100,
        "triggerPercentage": 1,
        "stopPercentage": 1.012,
        "limitPercentage": 1.0121
      },
      "sell": {
        "enabled": true,
        "triggerPercentage": 1.04,
        "stopPercentage": 0.99,
        "limitPercentage": 0.989
      }
    }
[2021-04-27T23:03:04.000Z]  INFO: binance-api/25 on 9612d846b41b: Configuration from MongoDB (version=0.0.65, server=websocket)
    payload: {
      "command": "latest",
      "data": {}
    }
    --
    globalConfiguration: {
      "_id": "6085e70294e5eefa25b715e1",
      "key": "configuration",
      "enabled": true,
      "cronTime": "* * * * * *",
      "symbols": [
        "BTCUSDT",
        "ETHUSDT",
        "BNBUSDT"
      ],
      "supportFIATs": [
        "USDT"
      ],
      "candles": {
        "interval": "1h",
        "limit": 100
      },
      "buy": {
        "enabled": true,
        "maxPurchaseAmount": 100,
        "triggerPercentage": 1,
        "stopPercentage": 1.012,
        "limitPercentage": 1.0121
      },
      "sell": {
        "enabled": true,
        "triggerPercentage": 1.04,
        "stopPercentage": 0.99,
        "limitPercentage": 0.989
      }
    }
[2021-04-27T23:03:04.000Z] ERROR: binance-api/25 on 9612d846b41b: Something wrong with trailing-trade-common cache (version=0.0.65, server=websocket, e={})
    payload: {
      "command": "latest",
      "data": {}
    }
[2021-04-27T23:03:04.001Z]  INFO: binance-api/25 on 9612d846b41b: Finding document from MongoDB (version=0.0.65, server=cronjob, job=trailingTrade, uuid=2d8745a0-b249-431e-a59d-b8e0f4bcf1b5, helper=mongo, funcName=findOne, collectionName=trailing-trade-common)
    query: {
      "key": "configuration"
    }
[2021-04-27T23:03:04.004Z]  INFO: binance-api/25 on 9612d846b41b: Found document from MongoDB (version=0.0.65, server=cronjob, job=trailingTrade, uuid=2d8745a0-b249-431e-a59d-b8e0f4bcf1b5, helper=mongo, funcName=findOne)
    result: {
      "_id": "6085e70294e5eefa25b715e1",
      "key": "configuration",
      "enabled": true,
      "cronTime": "* * * * * *",
      "symbols": [
        "BTCUSDT",
        "ETHUSDT",
        "BNBUSDT"
      ],
      "supportFIATs": [
        "USDT"
      ],
      "candles": {
        "interval": "1h",
        "limit": 100
      },
      "buy": {
        "enabled": true,
        "maxPurchaseAmount": 100,
        "triggerPercentage": 1,
        "stopPercentage": 1.012,
        "limitPercentage": 1.0121
      },
      "sell": {
        "enabled": true,
        "triggerPercentage": 1.04,
        "stopPercentage": 0.99,
        "limitPercentage": 0.989
      }
    }
[2021-04-27T23:03:04.005Z]  INFO: binance-api/25 on 9612d846b41b: Found configuration from MongoDB (version=0.0.65, server=cronjob, job=trailingTrade, uuid=2d8745a0-b249-431e-a59d-b8e0f4bcf1b5)
[2021-04-27T23:03:04.007Z]  INFO: binance-api/25 on 9612d846b41b: Cached last symbol (version=0.0.65, server=cronjob, job=trailingTrade, uuid=2d8745a0-b249-431e-a59d-b8e0f4bcf1b5, cachedLastSymbol=ETHUSDT)
[2021-04-27T23:03:04.007Z]  INFO: binance-api/25 on 9612d846b41b: Determined current symbol (version=0.0.65, server=cronjob, job=trailingTrade, uuid=2d8745a0-b249-431e-a59d-b8e0f4bcf1b5, currentSymbol=BNBUSDT)
[2021-04-27T23:03:04.008Z]  INFO: binance-api/25 on 9612d846b41b: Start step - get-exchange-symbol (version=0.0.65, server=cronjob, job=trailingTrade, uuid=2d8745a0-b249-431e-a59d-b8e0f4bcf1b5, stepName=get-exchange-symbol, symbol=BNBUSDT)
    data: {
      "globalConfiguration": {
        "_id": "6085e70294e5eefa25b715e1",
        "key": "configuration",
        "enabled": true,
        "cronTime": "* * * * * *",
        "symbols": [
          "BTCUSDT",
          "ETHUSDT",
          "BNBUSDT"
        ],
        "supportFIATs": [
          "USDT"
        ],
        "candles": {
          "interval": "1h",
          "limit": 100
        },
        "buy": {
          "enabled": true,
          "maxPurchaseAmount": 100,
          "triggerPercentage": 1,
          "stopPercentage": 1.012,
          "limitPercentage": 1.0121
        },
        "sell": {
          "enabled": true,
          "triggerPercentage": 1.04,
          "stopPercentage": 0.99,
          "limitPercentage": 0.989
        }
      },
      "symbol": "BNBUSDT",
      "symbolConfiguration": {},
      "accountInfo": {},
      "refreshAccountInfo": true,
      "indicators": {},
      "symbolInfo": {},
      "openOrders": [],
      "action": "not-determined",
      "baseAssetBalance": {},
      "quoteAssetBalance": {},
      "buy": {},
      "sell": {}
    }
`
Thank you`

**Comment by chrisleekr** [comment] 2021-04-28 07:37
@doyouknow93 Hmm, was there another error block before the first line?
```
    at dispatchRequest (/srv/node_modules/axios/lib/core/dispatchRequest.js:52:10)
```

**Comment by doyouknow93** [comment] 2021-04-28 11:15
Hi man, thank you for the support. The front end now work.

Only one question.
What is the difference from Target: dev-stage and Target: product stage?

Greettings

DYK

**Comment by chrisleekr** [comment] 2021-04-28 11:53
dev-stage is for development. 
production stage is for live use.

Please close the issue if your issue is resolved.

**Closed** 2021-04-28 11:54 UTC
Labels: bug
