### ISSUE TITLE
Slack doesn't work

### ISSUE THREAD

**Issue by 4KJuegos** [chrisleekr/binance-trading-bot#38] opened 2021-03-14 10:45 UTC
I don't know if i'm doing something wrong, I've put the URL on the env, and configured slack to recieve messages from user and bot, but nothing happens. Thanks!

**Comment by Maxoos** [comment] 2021-03-14 10:47
Look at the logs to spot if something is off.

`docker logs binance-bot`

**Comment by 4KJuegos** [comment] 2021-03-15 20:25
now works, but slack send me errors of certificate

**Comment by chrisleekr** [comment] 2021-03-16 11:24
What kind of errors are you seeing?

**Comment by chrisleekr** [comment] 2021-03-17 06:53
@4KJuegos I assume the issue is resolved as you didn't respond. Can you close the issue if it is resolved?

**Comment by 4KJuegos** [comment] 2021-03-17 07:11
no, is not resolved. I'm seeing this on Slack:

request to https://api.binance.com/api/v3/klines?interval=4h&symbol=TFUELUSDT&limit=5 failed, reason: Hostname/IP does not match certificate's altnames: Host: api.binance.com. is not in the cert's altnames: DNS:formrequests.com, DNS:zschoolcdnvideo.azureedge.net, DNS:e.stry.tl, DNS:zschoolcdn-static.azureedge.net, DNS:zschoolcdn-rsc.azureedge.net, DNS:www.formrequests.com, DNS:webdeskingapi.azureedge.net, DNS:videoscdo.azureedge.net, DNS:formrequests.azureedge.net, DNS:cdn.infocore.com, DNS:crl-immochan.azureedge.net, DNS:cdn.activplan.com, DNS:azwbsa1-cdn1.cfmdistributors.com, DNS:assets.askociety.com, DNS:sa354gl.wpc.edgecastcdn.net, DNS:cdn.uaccess.co.il, DNS:rsc.zschool.co.il, DNS:static.zschool.co.il, DNS:video.zschool.co.il, DNS:sa354gl.wpc.xicdn.net, DNS:sa362gl.wpc.edgecastcdn.net```Stack:```FetchError: request to https://api.binance.com/api/v3/klines?interval=4h&symbol=TFUELUSDT&limit=5 failed, reason: Hostname/IP does not match certificate's altnames: Host: api.binance.com. is not in the cert's altnames: DNS:formrequests.com, DNS:zschoolcdnvideo.azureedge.net, DNS:e.stry.tl, DNS:zschoolcdn-static.azureedge.net, DNS:zschoolcdn-rsc.azureedge.net, DNS:www.formrequests.com, DNS:webdeskingapi.azureedge.net, DNS:videoscdo.azureedge.net, DNS:formrequests.azureedge.net, DNS:cdn.infocore.com, DNS:crl-immochan.azureedge.net, DNS:cdn.activplan.com, DNS:azwbsa1-cdn1.cfmdistributors.com, DNS:assets.askociety.com, DNS:sa354gl.wpc.edgecastcdn.net, DNS:cdn.uaccess.co.il, DNS:rsc.zschool.co.il, DNS:static.zschool.co.il, DNS:video.zschool.co.il, DNS:sa354gl.wpc.xicdn.net, DNS:sa362gl.wpc.edgecastcdn.net
    at ClientRequest.<anonymous> (/srv/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by chrisleekr** [comment] 2021-03-17 07:15
@4KJuegos hey, that is nothing to do with the bot. Your internet (possibly router) is not able to connect  `api.binance.com`

When you access from the browser for the URL `view-source:https://api.binance.com/` 
```
 <!DOCTYPE html><html><head><title>Test OK</title></head><body></body></html>
```

If not, check your DNS. 

I close the issue as not relevant with the bot.

**Closed by chrisleekr** 2021-03-17 07:15 UTC
Labels: question

**Comment by donley828** [comment] 2021-05-17 09:14
> @4KJuegos hey, that is nothing to do with the bot. Your internet (possibly DNS configuration in your router) is not able to connect `api.binance.com`
> 
> When you access from the browser for the URL `view-source:https://api.binance.com/`
> 
> ```
>  <!DOCTYPE html><html><head><title>Test OK</title></head><body></body></html>
> ```
> 
> If not, check your DNS.
> 
> I close the issue as not relevant to the bot.

i visit view-source:https://api.binance.com/ is ok.but that error is still occured.
