### ISSUE TITLE
Run local without docker / cancel prints to log's

### ISSUE THREAD

**Issue by Nir-Cohen** [chrisleekr/binance-trading-bot#401] opened 2021-12-08 14:35 UTC
Hi,
I try to run this locally, not with docker -> npm run dev, is throw an errors about redis and mongo although the containers of them are still alive, I think its might be a bug. 

My question basically is, which logger is spamming the log like that?
wants to debug some area'a to do so improvements.

And, are you going to add support in binance features?

**Comment by chrisleekr** [comment] 2022-07-22 14:24
@Nir-Cohen Sorry for the late reply.

> My question basically is, which logger is spamming the log like that?

bunyan

> And, are you going to add support in binance features?

I don't understand your question.

I will close the issue for now as the issue is old. Please open a new issue if you have further questions.

**Closed by chrisleekr** 2022-07-22 14:24 UTC
Labels: question
