### ISSUE TITLE
how i solve this problem ?

### ISSUE THREAD

**Issue by zapotec001** [chrisleekr/binance-trading-bot#320] opened 2021-09-15 17:00 UTC
**"portainer compose version 3 not supported"**

I get this error when I add to **portainer**.
how can i solve this problem?

_(sorry for my bad english)_

**Comment by chrisleekr** [comment] 2021-09-15 22:01
First of all, it's not a bug. And please search for issues before posting.

Since I am not using Portainer, I am not sure how to fix it. 

Refer https://github.com/chrisleekr/binance-trading-bot/issues/114

Please close the issue.

**Closed** 2021-09-15 22:03 UTC
Labels: bug
