### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by bariscancamlidere** [chrisleekr/binance-trading-bot#32] opened 2021-03-09 07:18 UTC
Hi Chris,

It is a lovely bot. I setup and configured settings on Windows with using Docker Desktop. It works great for a time however approx. 1 hour 30 minutes the UI becomes unresponsive and only updates the time and does not gather any data. For now, I'm thinking a task scheduler to restart the docker after that time. Is it possible that you can take a look at that? I have decent internet connection and hardware. Thanks in advance.

Regards,
Bariscan

**Comment by Maxoos** [comment] 2021-03-09 07:51
It happened to me as well when using the tunnel. Without the tunnel it’s
fine. Also putting it on a server makes it much more stable.

**Comment by bariscancamlidere** [comment] 2021-03-09 08:12
Hi Maxoos,

Thank you for the reply. How did you disable the tunnel?

**Comment by chrisleekr** [comment] 2021-03-09 11:02
Hey @bariscancamlidere 

I don't have a Windows machine so I cannot test it out. 
I never had an issue with my browser for the frontend on my laptop and mobile.

If you can figure out what the issue is, it will be helpful for others.

**Comment by bariscancamlidere** [comment] 2021-03-09 11:17
> Hey @bariscancamlidere
> 
> I don't have a Windows machine so I cannot test it out.
> I never had an issue with my browser for the frontend on my laptop and mobile.
> 
> If you can figure out what the issue is, it will be helpful for others.
> I will open the issue in case others can answer.

How do we disable the tunnel like @Maxoos mentioned?
on .env -> BINANCE_LOCAL_TUNNEL_SUBDOMAIN=default
I deleted the default and re-docked the bot. Is it true?

**Comment by chrisleekr** [comment] 2021-03-09 11:29
@bariscancamlidere 
It doesn't have an option to turn off, which I may add later on.

But the Local Tunnel is just for the frontend thing. Even if it is on, it should not impact performance.
Although if you access via the Local Tunnel, it could get network issue if your internet is slow.

To workaround, simply access via the IP address of your server. i.e. `http://192.168.1.5:8080`

**Comment by bariscancamlidere** [comment] 2021-03-09 11:55
> @bariscancamlidere
> It doesn't have an option to turn off, which I may add later on.
> 
> But the Local Tunnel is just for the frontend thing. Even if it is on, it should not impact performance.
> Although if you access via the Local Tunnel, it could get network issue if your internet is slow.
> 
> To workaround, simply access via the IP address of your server. i.e. `http://192.168.1.5:8080`

@chrisleekr 
I'm not using the tunnel however after sometime it stops only updating a current time and does not retrieve any information and also I believe does not perform any actions after that. Restarting docker solves the problem. I will try to pinpoint the issue and try to check ws messages. I don't believe there is an issue with Binance API key because restarting the docker simply works. I will keep you updated. Thanks!

**Comment by bariscancamlidere** [comment] 2021-03-09 16:34
Hi again @chrisleekr,

I just checked again. It seems that the issue is related to only frontend. On background, it continues to work without a problem.

**Comment by chrisleekr** [comment] 2021-03-13 01:04
@bariscancamlidere 

Are you still experiencing the issue?
Can you tell me which browser you are using? 
And can you provide the browser screenshot of 
- Inspect -> Console
- Inspect -> Network -> WS

**Comment by 4KJuegos** [comment] 2021-03-14 10:39
Yesterday still experiencing the issue with frontend. How can we disable the Local Tunnel with new version?

**Comment by 4KJuegos** [comment] 2021-03-15 22:36
> Hi Maxoos,
> 
> Thank you for the reply. How did you disable the tunnel?

on .env --> BINANCE_LOCAL_TUNNEL_ENABLED=false

**Comment by chrisleekr** [comment] 2021-03-16 11:25
@4KJuegos What kind of issue were you having? Can you give details?

**Comment by chrisleekr** [comment] 2021-03-17 06:53
@4KJuegos I assume the issue is resolved. Can you close the issue?

**Comment by 4KJuegos** [comment] 2021-03-17 07:15
> @4KJuegos What kind of issue were you having? Can you give details?

The frontend now works perfectly on Raspberry Pi, i assume was a problem with Docker on Windows. For now, I'm only expereriencing the other issue with Slack. Thanks!

**Comment by chrisleekr** [comment] 2021-03-17 07:23
@4KJuegos good to hear. :) In that case, please close the issue. Thanks.

**Comment by bariscancamlidere** [comment] 2021-03-17 07:53
I couldn't test it yet. Give me some time to see.

**Comment by chrisleekr** [comment] 2021-03-24 03:55
@bariscancamlidere any issue so far? If not, please close the issue.

**Comment by chrisleekr** [comment] 2021-03-31 09:25
@bariscancamlidere I assume you don't have more issue as didn't have any feedback for 7days. I close the issue. If you have an issue, please open new issue.

**Closed by chrisleekr** 2021-03-31 09:25 UTC
Labels: help wanted
