### ISSUE TITLE
does not save the last purchase price trade bot

### ISSUE THREAD

**Issue by niyazikeklik** [chrisleekr/binance-trading-bot#116] opened 2021-04-26 07:31 UTC
Hello, I don't quite understand why. I was not in front of the computer, so I don't know what happened at that time, but the last purchase price was not recorded for the two orders below. I manually recorded it myself when I woke up in the morning. This is a very risky bug.

![image](https://user-images.githubusercontent.com/27292457/116045272-8e62e980-a67a-11eb-8a06-ad3f5a20e813.png)

**Comment by chrisleekr** [comment] 2021-04-26 09:34
Hey @niyazikeklik 

Are you using master version or #77 branch?

**Comment by niyazikeklik** [comment] 2021-04-26 09:37
git clone https://github.com/chrisleekr/binance-trading-bot.git

**Comment by niyazikeklik** [comment] 2021-04-26 09:39
I am less experienced in these matters.

I installed it with this command.
git clone https://github.com/chrisleekr/binance-trading-bot.git

How can I update if there is a new version available?

**Comment by chrisleekr** [comment] 2021-04-26 09:43
Hmm, so I assume you are using master version, which is stable.

Can you take a screenshot of the chart when the bot purchased price?

**Comment by niyazikeklik** [comment] 2021-04-26 10:17
![image](https://user-images.githubusercontent.com/27292457/116066788-15bb5780-a691-11eb-9220-99b95b110c18.png)

I'm not sure what I'm using. I am learning many things through your application.

-Virtual machine
-Linux
-Docker
-Go

So I run a lot of commands to try it out. Sometimes things can get messy. I don't know what I'm doing myself either. :) I'm sorry.

**Comment by chrisleekr** [comment] 2021-04-26 10:46
Hey @niyazikeklik 

I will need more information to find out what happened.

The chart you attached is for RVNUSDT?
Why there is selling text in the chart? Was it sold?

**Comment by niyazikeklik** [comment] 2021-04-26 10:49
No, he bought it last night, and when I woke up this morning, the purchase price didn't seem to be recorded. I saved it manually and then RVNUSDT was instantly dropped and sold.

**Comment by chrisleekr** [comment] 2021-04-26 10:51
Was the price dropped after bought?

> ![image](https://user-images.githubusercontent.com/27292457/116045272-8e62e980-a67a-11eb-8a06-ad3f5a20e813.png)

It looks like you only bought 14USDT, which is a small amount. If less than 10 USDT, the bot would remove the last buy price.

**Comment by niyazikeklik** [comment] 2021-04-26 10:59
No, I thought about that. The minimum price after purchase is 0.12095 i.e. 116 RVN = 14 USDT.

**Comment by chrisleekr** [comment] 2021-04-26 11:04
Right, that is very strange. Never had that issue with master branch.

The code to save the last buy price is this - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/place-buy-order.js#L121

As you can see, after placing the buy order, it saves into the mongodb, which is a persistent database.
It would not lose the price unless matching the condition in this file - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/remove-last-buy-price.js#L49

As I don't have any access on your bot or Binance, I won't be able to debug what actually happened.

If you are ok to use an unstable version, try to use this PR #77. This PR has a code that sends a notification when the last buy price is removed from the bot.

![image](https://user-images.githubusercontent.com/5715919/116072720-d1e94200-a6d2-11eb-9c8e-c8aee0efa57f.png)

Of course, you should use Slack to receive the notification.

**Comment by niyazikeklik** [comment] 2021-04-26 12:42
> Right, that is very strange. Never had that issue with master branch.
> 
> The code to save the last buy price is this - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/place-buy-order.js#L121
> 
> As you can see, after placing the buy order, it saves into the mongodb, which is a persistent database.
> It would not lose the price unless matching the condition in this file - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/jobs/trailingTrade/step/remove-last-buy-price.js#L49
> 
> As I don't have any access on your bot or Binance, I won't be able to debug what actually happened.
> 
> If you are ok to use an unstable version, try to use this PR #77. This PR has a code that sends a notification when the last buy price is removed from the bot.
> 
> ![image](https://user-images.githubusercontent.com/5715919/116072720-d1e94200-a6d2-11eb-9c8e-c8aee0efa57f.png)
> 
> Of course, you should use Slack to receive the notification.

How can I tell which version I am using?

**Comment by chrisleekr** [comment] 2021-04-26 12:47
Hmm... 
I know you mentioned you are not familiar with this kind of thing. I won't have time to teach you every single command to use.

Please do your own research. 
Thanks.

**Comment by chrisleekr** [comment] 2021-04-27 22:13
Please close the issue if the issue is resolved.

**Closed** 2021-04-28 07:39 UTC
Labels: bug
