### ISSUE TITLE
I cannot open 8080！Check the log, the error is as follows。WARNING: NODE_ENV value of 'production' did not match any deployment config file names.

### ISSUE THREAD

**Issue by Char1esOrz** [chrisleekr/binance-trading-bot#314] opened 2021-09-13 01:13 UTC
![image](https://user-images.githubusercontent.com/28600640/133010208-1fe8d125-6371-4e45-8d93-dcf7f5a003df.png)

**Comment by ilbuonmarcio** [comment] 2021-09-13 14:52
Did you edit some files in the process of getting it up and running?

**Comment by BartTechne** [comment] 2021-09-14 11:11
I have the same issue

**Comment by chrisleekr** [comment] 2021-09-14 21:49
Hey guys,

Please get the full log and put it here so I can see what is the issue - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

The warning message can be ignored.

**Comment by truonglehcm** [comment] 2021-09-16 19:15
Hello,

I'm also face this issue.
I don't know where i'm wrong.
I just do these steps:

1. create .env base on .env.dist
2. Add BINANCE_TEST_API_KEY and BINANCE_TEST_SECRET_KEY
3. Run docker-compose -f docker-compose.server.yml pull
4. Run docker-compose -f docker-compose.server.yml up -d

**Comment by ilbuonmarcio** [comment] 2021-09-16 19:19
Does it work if you use the master version?

By using:
docker-compose build
docker-compose up -d --build

**Comment by truonglehcm** [comment] 2021-09-16 21:04
No, it does not work.

I tried, but binance-bot container showing message "standard_init_linux.go:228: exec user process caused: no such file or directory". I'm using windows 11.

If i use commands below, it will run inside docker, but i can not access web from http://0.0.0.0:8080
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d

**Comment by ilbuonmarcio** [comment] 2021-09-17 16:22
It's indeed a bug, I'm also facing it with a fresh build from master using Docker for Windows on Windows 10, latest build available.

```
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
binance-mongo-express  | Waiting for binance-mongo:27017...
binance-mongo-express  | Welcome to mongo-express
binance-mongo-express  | ------------------------
binance-mongo-express  | 
binance-mongo-express  | 
binance-mongo-express  | Mongo Express server listening at http://0.0.0.0:8081
binance-mongo-express  | [31mServer is open to allow connections from anyone (0.0.0.0)[39m
binance-mongo-express  | [31mbasicAuth credentials are "admin:pass", it is recommended you change this in your config.js![39m
binance-mongo-express  | Database connected
binance-mongo-express  | Admin Database connected
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=54a4930a539d
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] db version v3.2.20
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] git version: a7a144f40b70bfe290906eb33ff2714933544af8
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] allocator: tcmalloc
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] modules: none
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] build environment:
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten]     distmod: debian81
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten]     distarch: x86_64
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten]     target_arch: x86_64
binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] options: {}
binance-mongo          | 2021-09-17T16:15:12.488+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
binance-mongo          | 2021-09-17T16:15:12.489+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=14G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
binance-mongo          | 2021-09-17T16:15:12.649+0000 I STORAGE  [initandlisten] WiredTiger [1631895312:649774][1:0x7faa8d205cc0], txn-recover: Main recovery loop: starting at 1/10368
binance-mongo          | 2021-09-17T16:15:12.761+0000 I STORAGE  [initandlisten] WiredTiger [1631895312:761392][1:0x7faa8d205cc0], txn-recover: Recovering log 1 through 2
binance-mongo          | 2021-09-17T16:15:12.855+0000 I STORAGE  [initandlisten] WiredTiger [1631895312:855340][1:0x7faa8d205cc0], txn-recover: Recovering log 2 through 2
binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] 
binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] 
binance-mongo          | 2021-09-17T16:15:12.941+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
binance-mongo          | 2021-09-17T16:15:12.941+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
binance-mongo          | 2021-09-17T16:15:12.941+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
binance-mongo          | 2021-09-17T16:15:13.148+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:38402 #1 (1 connection now open)
binance-mongo          | 2021-09-17T16:15:13.148+0000 I NETWORK  [conn1] end connection 172.18.0.3:38402 (0 connections now open)
binance-mongo          | 2021-09-17T16:15:13.441+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:38404 #2 (1 connection now open)
binance-redis          | 1:C 17 Sep 2021 16:15:13.621 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
binance-redis          | 1:C 17 Sep 2021 16:15:13.621 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
binance-redis          | 1:C 17 Sep 2021 16:15:13.621 # Configuration loaded
binance-redis          | 1:M 17 Sep 2021 16:15:13.621 * monotonic clock: POSIX clock_gettime
binance-redis          | 1:M 17 Sep 2021 16:15:13.622 * Running mode=standalone, port=6379.
binance-redis          | 1:M 17 Sep 2021 16:15:13.622 # WARNING: The TCP backlog setting of 65536 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 1024.
binance-redis          | 1:M 17 Sep 2021 16:15:13.622 # Server initialized
binance-redis          | 1:M 17 Sep 2021 16:15:13.622 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
binance-redis          | 1:M 17 Sep 2021 16:15:13.622 * Ready to accept connections
```

From what I'm reading online it's a CRLF problem occurring in Windows only, I'll provide a patch asap

**Comment by truonglehcm** [comment] 2021-09-17 21:06
Hi Bro,

Thank you,
By adding a comment as you fixed inside _image-files/usr/local/bin/docker-entrypoint.sh_
I can build "docker-compose up -d --build" and it up on docker
But, I still does not access localhost:8080

I'm following DEVELOPMENT.md guide

**Comment by ilbuonmarcio** [comment] 2021-09-17 22:13
You need to also use

docker-compose build

first

**Comment by truonglehcm** [comment] 2021-09-18 17:13
Yes, I did

**Comment by chrisleekr** [comment] 2021-09-19 04:46
> * create .env base on .env.dist
> * Add BINANCE_TEST_API_KEY and BINANCE_TEST_SECRET_KEY
> * Run docker-compose -f docker-compose.server.yml pull
> * Run docker-compose -f docker-compose.server.yml up -d

You are using the test API key for live mode.
That is why it's not working.
If you want to run test mode, change `BINANCE_MODE`
https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L13

**Comment by chrisleekr** [comment] 2021-09-19 05:00
> It's indeed a bug, I'm also facing it with a fresh build from master using Docker for Windows on Windows 10, latest build available.
> 
> ```
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory
> binance-mongo-express  | Waiting for binance-mongo:27017...
> binance-mongo-express  | Welcome to mongo-express
> binance-mongo-express  | ------------------------
> binance-mongo-express  | 
> binance-mongo-express  | 
> binance-mongo-express  | Mongo Express server listening at http://0.0.0.0:8081
> binance-mongo-express  | �[31mServer is open to allow connections from anyone (0.0.0.0)�[39m
> binance-mongo-express  | �[31mbasicAuth credentials are "admin:pass", it is recommended you change this in your config.js!�[39m
> binance-mongo-express  | Database connected
> binance-mongo-express  | Admin Database connected
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=54a4930a539d
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] db version v3.2.20
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] git version: a7a144f40b70bfe290906eb33ff2714933544af8
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] allocator: tcmalloc
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] modules: none
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] build environment:
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten]     distmod: debian81
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten]     distarch: x86_64
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten]     target_arch: x86_64
> binance-mongo          | 2021-09-17T16:15:12.486+0000 I CONTROL  [initandlisten] options: {}
> binance-mongo          | 2021-09-17T16:15:12.488+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
> binance-mongo          | 2021-09-17T16:15:12.489+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=14G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
> binance-mongo          | 2021-09-17T16:15:12.649+0000 I STORAGE  [initandlisten] WiredTiger [1631895312:649774][1:0x7faa8d205cc0], txn-recover: Main recovery loop: starting at 1/10368
> binance-mongo          | 2021-09-17T16:15:12.761+0000 I STORAGE  [initandlisten] WiredTiger [1631895312:761392][1:0x7faa8d205cc0], txn-recover: Recovering log 1 through 2
> binance-mongo          | 2021-09-17T16:15:12.855+0000 I STORAGE  [initandlisten] WiredTiger [1631895312:855340][1:0x7faa8d205cc0], txn-recover: Recovering log 2 through 2
> binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] 
> binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
> binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
> binance-mongo          | 2021-09-17T16:15:12.940+0000 I CONTROL  [initandlisten] 
> binance-mongo          | 2021-09-17T16:15:12.941+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
> binance-mongo          | 2021-09-17T16:15:12.941+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
> binance-mongo          | 2021-09-17T16:15:12.941+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
> binance-mongo          | 2021-09-17T16:15:13.148+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:38402 #1 (1 connection now open)
> binance-mongo          | 2021-09-17T16:15:13.148+0000 I NETWORK  [conn1] end connection 172.18.0.3:38402 (0 connections now open)
> binance-mongo          | 2021-09-17T16:15:13.441+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:38404 #2 (1 connection now open)
> binance-redis          | 1:C 17 Sep 2021 16:15:13.621 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> binance-redis          | 1:C 17 Sep 2021 16:15:13.621 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
> binance-redis          | 1:C 17 Sep 2021 16:15:13.621 # Configuration loaded
> binance-redis          | 1:M 17 Sep 2021 16:15:13.621 * monotonic clock: POSIX clock_gettime
> binance-redis          | 1:M 17 Sep 2021 16:15:13.622 * Running mode=standalone, port=6379.
> binance-redis          | 1:M 17 Sep 2021 16:15:13.622 # WARNING: The TCP backlog setting of 65536 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 1024.
> binance-redis          | 1:M 17 Sep 2021 16:15:13.622 # Server initialized
> binance-redis          | 1:M 17 Sep 2021 16:15:13.622 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> binance-redis          | 1:M 17 Sep 2021 16:15:13.622 * Ready to accept connections
> ```
> 
> From what I'm reading online it's a CRLF problem occurring in Windows only, I'll provide a patch asap

I will merge the fix to address CRLF issue.

**Comment by chrisleekr** [comment] 2021-09-19 05:01
@Char1esOrz 

If your issue is resolved, please close the issue. Otherwise, I will close soon.

**Comment by truonglehcm** [comment] 2021-09-19 05:28
> 
> 
> > * create .env base on .env.dist
> > * Add BINANCE_TEST_API_KEY and BINANCE_TEST_SECRET_KEY
> > * Run docker-compose -f docker-compose.server.yml pull
> > * Run docker-compose -f docker-compose.server.yml up -d
> 
> You are using the test API key for live mode.
> That is why it's not working.
> If you want to run test mode, change `BINANCE_MODE`
> https://github.com/chrisleekr/binance-trading-bot/blob/master/docker-compose.server.yml#L13

Hello Chris,

Below are my configure files:

1.  .env
## Live
BINANCE_LIVE_API_KEY=
BINANCE_LIVE_SECRET_KEY=

## Test
BINANCE_TEST_API_KEY=OTUurI6U02CiTspC5mr4GMHUtGT5jRhTm93s8VdzqbMLs4uOfSIBe5DmGHd0ELd
BINANCE_TEST_SECRET_KEY=feD9yGIfHRJ3XaPLk4IfMEGb18vCedIQUncjB3bZzULMoXIzVd45eUm7cEelpJI

## Slack
BINANCE_SLACK_ENABLED=false
BINANCE_SLACK_WEBHOOK_URL=
BINANCE_SLACK_CHANNEL=
BINANCE_SLACK_USERNAME=

## Local Tunnel
BINANCE_LOCAL_TUNNEL_ENABLED=false
### A local tunnel makes the bot accessible from the outside.
### Please set the subdomain of the local tunnel as a subdomain that only you can remember.
BINANCE_LOCAL_TUNNEL_SUBDOMAIN=default

## Feature Toggles
BINANCE_FEATURE_TOGGLE_NOTIFY_ORDER_CONFIRM=true
BINANCE_FEATURE_TOGGLE_NOTIFY_DEBUG=false
BINANCE_FEATURE_TOGGLE_NOTIFY_ORDER_EXECUTE=true

## Authentication
BINANCE_AUTHENTICATION_ENABLED=true
### Please set your own password.
BINANCE_AUTHENTICATION_PASSWORD=123456
BINANCE_JOBS_TRAILING_TRADE_BOT_OPTIONS_AUTHENTICATION_LOCK_LIST=true
BINANCE_JOBS_TRAILING_TRADE_BOT_OPTIONS_AUTHENTICATION_LOCK_AFTER=120

2. docker-compose.server.yml
version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    image: chrisleekr/binance-trading-bot:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - BINANCE_MODE=test
      # - BINANCE_MODE=live
      - BINANCE_REDIS_HOST=binance-redis
      - BINANCE_REDIS_PORT=6379
      - BINANCE_REDIS_PASSWORD=secretp422
    ports:
      - 8080:80
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  binance-redis:
    container_name: binance-redis
    image: redis:6.2
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass secretp422

  binance-mongo:
    container_name: binance-mongo
    image: mongo:3.2.20-jessie
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

networks:
  internal:
    driver: bridge
    # driver_opts:
    #     com.docker.network.driver.mtu: 1442

volumes:
  redis_data:
  mongo_data:

**Comment by chrisleekr** [comment] 2021-09-19 08:29
@truonglehcm 

Are you still having the below issue?

> I tried, but binance-bot container showing message "standard_init_linux.go:228: exec user process caused: no such file or directory". I'm using windows 11.

As @ilbuonmarcio mentioned, it's crlf issue. I just merged `.gitattributes` to fix that issue.

You mentioned this as well, so I am confused now.

> By adding a comment as you fixed inside image-files/usr/local/bin/docker-entrypoint.sh
 
What issues are you having? Have you seen Troubleshooting wiki?
https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

**Comment by truonglehcm** [comment] 2021-09-19 14:28
> 
> 
> @truonglehcm
> 
> Are you still having the below issue?
> 
> > I tried, but binance-bot container showing message "standard_init_linux.go:228: exec user process caused: no such file or directory". I'm using windows 11.
> 
> As @ilbuonmarcio mentioned, it's crlf issue. I just merged `.gitattributes` to fix that issue.
> 
> You mentioned this as well, so I am confused now.
> 
> > By adding a comment as you fixed inside image-files/usr/local/bin/docker-entrypoint.sh
> 
> What issues are you having? Have you seen Troubleshooting wiki?
> https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

1. I'm not facing this issue "binance-bot  | standard_init_linux.go:228: exec user process caused: no such file or directory" - CRLF
2. I'm still facing the issue about localhost:8080

Let's me explain more detail:

1. First, i cloned project then:
- Create .env file based on .env.dist (update BINANCE_TEST_API_KEY and BINANCE_TEST_SECRET_KEY)
- Run commands to pull image from docker hub
```
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d
```
- Open browser http://0.0.0.0:8080 to see the frontend
=> I can't open (I pruned the image and tried again from your guide [#319](https://github.com/chrisleekr/binance-trading-bot/issues/319))

2. After that I tried with @ilbuonmarcio  suggestion by running these commands:
```
docker-compose build
docker-compose up -d --build

```
While I was trying this, the issue "standard_init_linux.go:228: exec user process caused: no such file or directory" happended.
Then, I follow #326 to fixed from my local workspace, now i'm not facing this issue. But, i still not access http://0.0.0.0:8080

**Comment by truonglehcm** [comment] 2021-09-19 15:53
@chrisleekr , @ilbuonmarcio 

Thank you so much guys.
I can open localhost:8080 now.

The issue is [clock-desync](https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-fix-clock-desync)

**Comment by chrisleekr** [comment] 2021-09-19 22:15
Good @truonglehcm 

Since @Char1esOrz does not respond whether his issue is resolved or not, I will close the issue. 
Please reopen if you face a new issue.

**Closed by chrisleekr** 2021-09-19 22:15 UTC
Labels: question
