### ISSUE TITLE
Does the number of symbol pairs affect program speed?

### ISSUE THREAD

**Issue by niyazikeklik** [chrisleekr/binance-trading-bot#109] opened 2021-04-22 19:48 UTC
I'm testing the bot on a modestly equipped virtual server. When I followed 6-10 pairs of symbols, I observed that the instant price withdrawal rate of the program decreased. There may even be delays in issuing stop loss orders. Is there anything I should know about this?

I have been running the server for 10 days without interruption. maybe this is the reason.

System features;
Standart B2s (2 vcpu count, 4 GiB memory)

**Comment by FOXGLove81** [comment] 2021-04-23 08:49
Now the bot checks pairs of characters in turn, but the WebSocket is being tested.
"_Previously, the job was monitoring each coin per second. However, now it monitors all the coins every second._"
https://github.com/chrisleekr/binance-trading-bot/pull/77

**Comment by chrisleekr** [comment] 2021-04-23 09:19
@niyazikeklik 

@FOXGLove81 is right. The current master version is checking a symbol per seconds.
If you have more symbols, each symbol will be checked slowly.

But I kind of sense, you are saying actual performance is decreased, which shouldn't be. 
Delays in the order most likely caused by the Binance. Sometimes, Binance returns the order result 1-3 seconds. 

It is ok to restart a bot every hour or every day.

As this bot is even running in the Raspberry Pi, your spec seems alright.

**Comment by niyazikeklik** [comment] 2021-04-23 10:39
Maybe it should be a priority system.

For example, if coin A has its last purchase value, it must be checked every second.
If coin B needs to drop more than 10% to trigger the buy signal, coin B needs to be checked every 1 minutes.

Likewise, if token A needs to increase more than 10% to be sold, 1 minutes must be waited.

Rates or durations can be adjusted either. Just an idea.

**Comment by chrisleekr** [comment] 2021-04-23 10:42
@niyazikeklik Thanks for the suggestion.

As @FOXGLove81 mentioned, #77 is waiting to be merged (doing an intensive test to make sure it works) which makes the coins being checked every second.

**Closed** 2021-04-23 10:50 UTC
Labels: question
