### ISSUE TITLE
CORS Error accessing from LAN

### ISSUE THREAD

**Issue by AllirionX** [chrisleekr/binance-trading-bot#141] opened 2021-05-02 10:18 UTC
I have the bot deployed on a raspberry pi 4. 

```
npm run docker:build
docker-compose -f docker-compose.rpi.yml up -d
```

It was running fine yesterday, but today after restarting I am getting CORS errors when accessing from the LAN with chrome or firefox.

`Access to script at 'https://unpkg.com/react@17/umd/react.development.js' from origin 'http://myip:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

If I disable the the web-security in chrome the web ui loads fine.

**Comment by chrisleekr** [comment] 2021-05-02 10:48
I am also having this issue. As you can see from the error message, it's not the bot. It is unpkg currently being not accessible for some reason.
Since the frontend is relying on their service, just have to wait.

**Comment by chrisleekr** [comment] 2021-05-02 14:35
The issue with unpkg.com seems to persist. If it is continuously happening until tomorrow, I may need to find an alternative way.

**Comment by chrisleekr** [comment] 2021-05-03 10:18
@AllirionX I think the issue is resolved. Please close the issue if your issue has been resolved.

**Closed** 2021-05-03 22:14 UTC
Labels: bug
