### ISSUE TITLE
can't connect the mongodb.

### ISSUE THREAD

**Issue by wobrawu** [chrisleekr/binance-trading-bot#65] opened 2021-03-30 05:31 UTC
install the bot by the docker step by step.but can't connect the mongodb.the error msg is:

{"name":"binance-api","version":"0.0.65","hostname":"ba34d97d72c3","pid":17,"level":30,"NODE_ENV":"production","msg":"API logger loaded","time":"2021-03-30T05:28:12.841Z","v":0}
{"name":"binance-api","version":"0.0.65","hostname":"ba34d97d72c3","pid":17,"helper":"mongo","level":30,"uri":"mongodb://binance-mongo:27017/?poolSize=20&retryWrites=true&writeConcern=majority","msg":"Connecting mongodb","time":"2021-03-30T05:28:13.302Z","v":0}
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/srv/node_modules/ioredis/built/redis/index.js:308:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by chrisleekr** [comment] 2021-03-31 09:24
This is not a bug. 

And the log said, it cannot connect Redis, not MongoDB. 
You need to check what happened to the Redis container.

**Comment by chrisleekr** [comment] 2021-04-02 11:45
I will close the issue as I didn't get any feedback from you. Please open new issue if you still have an issue.

**Closed by chrisleekr** 2021-04-02 11:45 UTC
Labels: bug
