### ISSUE TITLE
Error: Timestamp 

### ISSUE THREAD

**Issue by alexmdcampo** [chrisleekr/binance-trading-bot#572] opened 2023-01-02 18:48 UTC
## Version
v0.0.96

## Description

I'm stuck in Failed to load your account information screen

I review API's keys using in test mode

Windows 10
docker {
Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64}

{"name":"binance-api","version":"0.0.96","hostname":"865d306ace56","pid":46,"gitHash":"209d2e0","level":50,"err":{"message":"Timestamp for this request is outside of the recvWindow.","name":"Error","stack":"Error: Timestamp for this request is outside of the recvWindow.\n    at /srv/node_modules/binance-api-node/dist/http-client.js:100:17\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async m (/srv/dist/server.js:1:65632)\n    at async k (/srv/dist/server.js:1:136760)\n    at async /srv/dist/server.js:1:138072\n    at async runBinance (/srv/dist/server.js:1:137374)\n    at async Promise.all (index 0)\n    at async /srv/dist/server.js:1:146985","code":-1021},"msg":"Timestamp for this request is outside of the recvWindow.","time":"2023-01-02T18:37:46.966Z","v":0}

## To Reproduce

run master

**Comment by alexmdcampo** [comment] 2023-01-02 19:23
I found a possible fix.

includes recWindow time

app/cronjog/trailingTradeHelper/common.js

const getAccountInfoFromAPI = async logger => {
   logger.info({ tag: 'get-account-info' }, 'Retrieving account info from API');
   const accountInfo = await binance.client.accountInfo({'recvWindow': 59000});


and it worked!

**Comment by chrisleekr** [comment] 2023-01-03 10:50
It is not a bug from the bot.

Read this troubleshooting doc - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-fix-clock-desync

Please close the issue if it's resolved.

**Closed** 2023-01-03 11:33 UTC
Labels: bug
