### ISSUE TITLE
Issues staring the app.

### ISSUE THREAD

**Issue by georgeiliadis91** [chrisleekr/binance-trading-bot#113] opened 2021-04-24 14:19 UTC
I have gone through the setup filled the env values (except the binance test tokens) and created a fresh binance account as well a slack channel and added the localtunnel URL on the application/ 

But when launching the app its stuck at loading. Could you update the docs to be a little more detailed with the setup process. 
Thanks.

**Comment by chrisleekr** [comment] 2021-04-25 03:25
Please check the log - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by daehli** [comment] 2021-04-25 04:36
Hello @georgeiliadis91 ,

In the `docker-compose.yml`, you can add this variable `BINANCE_SLACK_ENABLED=false`

![image](https://user-images.githubusercontent.com/6981314/115980897-215a3180-a55e-11eb-9f0c-28c0f293ac88.png)

BINANCE_SLACK_ENABLED is a required value. (From my understanding)

Cheer

**Comment by artifexor** [comment] 2021-04-25 14:53
Similar problem here, I created binance API keys (test+live), created new slack access, got the webhook url, all put into .env, copied from web page via clipboard. Added the BINANCE_SLACK_ENABLED to yml. Trading bot webpage is not loading and I got the following error:

```
[2021-04-25T14:27:13.336Z] ERROR: binance-api/37 on XXX: Execution failed. (version=0.0.65, server=cronjob, job=trailingTrade, uuid=XXX, symbol=BNBUSDT, err.code=-2015)
    Error: Invalid API-key, IP, or permissions for action.
        at /srv/node_modules/binance-api-node/dist/http-client.js:93:17
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async execute (/srv/app/jobs/trailingTrade/step/get-account-info.js:23:23)
        at async execute (/srv/app/jobs/trailingTrade.js:98:14)
        at async CronJob.<anonymous> (/srv/app/server-cronjob.js:29:11)
```

I copied the key+secret key via clipboard directly from binance page so I do not think there is any problem in them. No IP restriction enabled yet.

(What is difference between test and live binance API access at binance configuration? I created two similar API entry. Is there any difference in selectable options? Might this error is related to the option.)

**Comment by daehli** [comment] 2021-04-25 15:04
Hi @artifexor , 

If you are using the `BINANCE_MODE='test'` you need to create an `API KEY` & `SECRET` for this URL `https://testnet.binance.vision`. https://github.com/chrisleekr/binance-trading-bot/blob/master/app/helpers/binance.js#L11

I forgot to add I used the `BINANCA_MODE='live'` in my .env

Cheer

**Comment by artifexor** [comment] 2021-04-25 15:17
@daehli Thank you very much, this testnet stuff was the solution, now it is working fine. Cheers

**Comment by chrisleekr** [comment] 2021-04-26 09:36
Please close the issue of the issue is resolved.

**Comment by georgeiliadis91** [comment] 2021-04-26 10:44
I will later tonight, havent gotten around testing the suggested solution.

**Comment by shah-harshit** [comment] 2021-04-26 11:27
I would to contribute to this project, how can i help?

**Comment by chrisleekr** [comment] 2021-04-26 11:48
@shah-harshit 

You are more than welcome to contribute. I have a list of things to do on the TODO list.
However, I have done massive refactoring of the code in this PR - #77 (comment)
So you may want to wait for this merge or branch out from this PR branch.
In the PR, I have some enhancements are already done from the TODO list.

If you still want, simply take a task from here - https://github.com/chrisleekr/binance-trading-bot#changes--todo
And push the PR first to make sure to let others know you are working on it.
Then others will not take what you are working on it.

**Make sure you branch out from PR #77.** 

Also, make sure you link the issue in the PR like below:
![image](https://user-images.githubusercontent.com/5715919/116077485-e29cb680-a6d8-11eb-8443-c8a36244f08a.png)

I should've added CONTRIBUTING.md. Just don't have much time to add it.

**Closed** 2021-04-26 19:06 UTC
Labels: question
