### ISSUE TITLE
Stuck UI refreshing circle

### ISSUE THREAD

**Issue by gsapounas** [chrisleekr/binance-trading-bot#98] opened 2021-04-14 11:59 UTC
## Description

Maybe im doing sth wrong but when i build the app and running the frontend from the browser it doesnt load and keeps refreshing..

**Comment by chrisleekr** [comment] 2021-04-14 12:02
Please check binance bot log

https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by gsapounas** [comment] 2021-04-14 12:14
after checking the log it outputs this:

[2021-04-14T12:13:21.134Z] ERROR: binance-api/37 on 42511f99a427: Something wrong with trailing-trade-common cache (version=0.0.65, server=websocket, e={})
    payload: {
      "command": "latest",
      "data": {}
    }

**Comment by RomanGorbatko** [comment] 2021-04-15 23:53
@chrisleekr Have the same problem https://prnt.sc/11h8yqf

**Comment by RomanGorbatko** [comment] 2021-04-16 00:30
Oh sorry, the only problem that I'm using test mode with live credentials.

**Comment by chrisleekr** [comment] 2021-04-16 06:02
@gsapounas Something must be wrongly configured. 
The log you posted is websocket log. Try to get the cronjob log using below command:

```
reset; docker logs binance-bot  -f --tail=100 | bunyan -c 'this.server == "cronjob"' 
```

Or using this command to get the log after restarting the bot

```
reset; docker logs binance-bot  -f --since=1m | less 
```

**Comment by chrisleekr** [comment] 2021-04-16 22:23
@gsapounas Please close the issue if the issue is resolved.

**Closed** 2021-04-18 04:15 UTC
Labels: bug
