### ISSUE TITLE
Error: Way too much request weight used; IP banned until ....

### ISSUE THREAD

**Issue by claytonnarcis** [chrisleekr/binance-trading-bot#251] opened 2021-07-30 09:25 UTC
## Description

Hi,
I'm using v0.0.73 (a7d650b) and got this error.

`
Job: Trailing Trade Indicator
Code: -1003
Message:
Way too much request weight used; IP banned until 1627635599203. Please use the websocket for live updates to avoid bans.
`

I'm currently only monitoring 6 symbols with a buying signal (15m). 

What i can do to reduce the interval and avoid using too much weight in a short time?

Thank you!

**Comment by claytonnarcis** [comment] 2021-07-30 09:31
Another question. 
Is there a reason why websocket is not used for live updates?

Might give a go to implement if it's just time/effort on your end.

**Comment by chrisleekr** [comment] 2021-07-30 09:33
Hi @claytonnarcis 

I am also monitoring 6 symbols with 15m/30. 

>Is there a reason why websocket is not used for live updates?

FYI, WebSocket is used to retrieve the current price.

Let me confirm with you few things:
1. Can you show me your symbol configuration?
2. Did you have many open orders?

**Comment by claytonnarcis** [comment] 2021-07-30 09:37
1.) Here you go.
<img width="536" alt="Screenshot 2021-07-30 at 5 33 50 PM" src="https://user-images.githubusercontent.com/262120/127633530-6d1afa60-52e3-4d94-a555-63cc6c35a28f.png">

2.) None. All waiting to execute.

Prior to this ban alert. This error popup.

`
Execution failed (08:34:59.588)
Job: Trailing Trade Indicator
Code: -1003
Message:
Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
`

**Comment by chrisleekr** [comment] 2021-07-30 09:40
Really? There were no open orders?

Hmm, something else is going on.

Can you see the bottom of the frontend which will show the usage of API like below:
![image](https://user-images.githubusercontent.com/5715919/127634370-ef4c05d0-edfd-4062-ba67-c6bd4a9614b6.png)

Can you check what was the maximum used weight?

**Comment by claytonnarcis** [comment] 2021-07-30 09:44
Here are some screenshots from Slack.

<img width="970" alt="Screenshot 2021-07-30 at 5 43 07 PM" src="https://user-images.githubusercontent.com/262120/127634792-a3610c62-9f14-4ddb-8a10-7a99ce26e47b.png">

<img width="952" alt="Screenshot 2021-07-30 at 5 43 21 PM" src="https://user-images.githubusercontent.com/262120/127634818-5bde2be9-6a2c-4c4f-9d93-9ddbcbc6ba04.png">

**Comment by chrisleekr** [comment] 2021-07-30 09:54
Can you run following command in your server and provide me the log?

```docker logs binance-bot -f | bunyan -c 'this.job === "trailingTradeIndicator"' > test.log```

In the log, it will display `apiLimit` that was used, so we can calculate how much the request used the API.

**Comment by chrisleekr** [comment] 2021-07-30 09:56
Before the alert that 1269 weight is used, were there any orders placed? 
I know you mentioned there was no open order, just want to make sure.

**Comment by claytonnarcis** [comment] 2021-07-30 09:58
hang on, let me double check.

**Comment by claytonnarcis** [comment] 2021-07-30 10:14
1. my bad, there were two open orders and then i got ban.
Refresh my IP, trade was executed.

Let me know if you need the order history and trades history screenshot from the binance app

2. Running bunyan threw errors like this
`(node:46) UnhandledPromiseRejectionWarning: LockError: Exceeded 1 attempts to lock the resource "redlock:trailing-trade-symbols:ETHUPUSDT-symbol-info".
    at /srv/node_modules/redlock/redlock.js:431:20
    at tryCatcher (/srv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/srv/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/srv/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/srv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/srv/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/srv/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/srv/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/srv/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
`
[trailing-indicator-cn.log](https://github.com/chrisleekr/binance-trading-bot/files/6906819/trailing-indicator-cn.log)

**Comment by chrisleekr** [comment] 2021-07-30 10:22
The trailingTradeIndicator processes following steps:
- https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTradeIndicator.js#L64

1. Get symbol configuration - does not use API
2. Get override action - does not use API
3. Execute dust transfer - if you execute dust transfer, it uses 1 API weight
4. Get account info - uses 10 API weights per second = maximum 600 API limits per min
5. Get indicators - uses 2 API weights per second = maximum 120 API weights per min.
6. Get open orders - uses 3 API weights per second = maximum 180 API weights per min.
7. Save data to cache - does not use API.

So in maximum with trailing trade indicators, it should use 900 API weights, but usually less than 900 because the trailingTradeIndicator takes more than 1 sec.  

> my bad, there were two open orders and then i got ban.
Refresh my IP, trade was executed.

The trailingTrade cronjob without orders does not use API; however, when there are open orders, it checks the order status based on the `checkOrderExecutePeriod` specified in the config.

Since you had some open orders, which still does not make sense because it was only 2 open orders.
My suspicion is the symbol ETHDOWNUSDT was down dramatically and cancel/place lots of orders within a min.
But still does not make sense because each order should have 20 seconds cool time `temporaryDisableActionAfterConfirmingOrder` and 10 seconds of checking order status `checkOrderExecutePeriod`.
https://github.com/chrisleekr/binance-trading-bot/blob/master/config/default.json#L92

Have you changed the config?

**Comment by chrisleekr** [comment] 2021-07-30 10:39
I cannot find any issue with your configuration. 

Hey, can you see at the bottom of the frontend how much is maximum API used weight per min?

Mine is typically about 550~600.

**Comment by claytonnarcis** [comment] 2021-07-30 10:45
will monitor, it's 16 right now. No open buy orders.

**Comment by chrisleekr** [comment] 2021-07-30 10:47
Let me know, it could be a bug that I didn't find.
Another suggestion I can make is increasing `checkOrderExecutePeriod` to 20 or something. 
- https://github.com/chrisleekr/binance-trading-bot/blob/master/config/default.json#L97

You can configure `BINANCE_JOBS_TRAILING_TRADE_SYSTEM_CHECK_ORDER_EXECUTE_PERIOD=20` in the `.env` file.

**Comment by claytonnarcis** [comment] 2021-07-30 11:35
Sure thing, will delay the check order.

Triggered by the grid trade.

**Comment by chrisleekr** [comment] 2021-07-30 11:52
Good, let me know. If the issue is not occurring again, please close the issue.

**Comment by pedrohusky** [comment] 2021-07-30 13:18
Hi Chris. A friend was having the same issues at my fork. Then he pulled your master version, erased docker data and got the bot up. He was instantly banned by IP, he monitored +-12 symbols.

After he had those problems, I went further and tried to change how the bot works, and I possibly found a way to keep the weight low while having various coins and not hurting much the bot update values performance.

I think the changes I did was:

- Add a seconds verify at every API call. This makes sure the same coin won't trigger the same steps over and over again.

- As I needed a different way to setup a last buy price, I did a 'order verification' code at ensure-order-placed.js that now tells the bot if the order was filled or not (I used the ensure-manual-buy-order.js code).

- If I'm not wrong, the coin won't be stuck too at the same step, before my changes it seems the bot could actually stuck at a step and then will trigger that step eternally, increasing API usage possibly.

 There was more changes, but I'm just writing them to give you a notion.

It was your master version 0.72 btw that he received the ban.

**Comment by chrisleekr** [comment] 2021-07-31 21:35
@pedrohusky 

> After those steps I can monitor almost 20 coins without even reaching 800 weight.

The bot itself is designed to monitor as many coins as configured. It supposes to not over 900 API weight limits per min. 

I am sure you already know by looking at the code. API requests are mostly done in the trailing trade indicators cronjob.
And in the trailing trade cronjob is only doing create/query/cancel orders. Those calls cost only 1 API weight per call.

@claytonnarcis 

A few weeks ago, I had received the API limit exceeded and found refreshing account information costing 20 API limit, not 10 API limit - https://binance-docs.github.io/apidocs/spot/en/#account-information-user_data

It should've cost only 10 API limit per call. After a few hours later, it's back to 10 API weight.

Hence, I added this configuration to reduce the call for refreshing account information, which is currently set as 1.
If it happens again, you can try increasing this as well.

```
"refreshAccountInfoPeriod": {
  "__name": "BINANCE_JOBS_TRAILING_TRADE_SYSTEM_REFRESH_ACCOUNT_INFO_PERIOD",
  "__description": "Set the seconds for the period of checking the account info.",
  "__format": "number"
}
```

Anyway, if the issue is not occurring continuously, please close the issue.

**Closed** 2021-08-01 12:28 UTC
Labels: question

**Comment by chopeta** [comment] 2021-09-19 23:43
Just wanna say thanks for this fix.

I am using a 40 pairs configuration with BUSD and a 6 grid trade config. for buying and when market went down I had more than 12 orders created by the bot and a lot of this API weight error msg. showing up on Slack.

After changing by config. according to this issue, everything seems to be good.

I've just added the folowing lines into the .env config. file and restarted the bot.

<code>
# See https://github.com/chrisleekr/binance-trading-bot/issues/251
BINANCE_JOBS_TRAILING_TRADE_SYSTEM_CHECK_ORDER_EXECUTE_PERIOD=20
BINANCE_JOBS_TRAILING_TRADE_SYSTEM_REFRESH_ACCOUNT_INFO_PERIOD=2
</code>

Thanks guys.
