### ISSUE TITLE
Help wanted to test PR - Updated for monitoring multiple coins simultaneously

### ISSUE THREAD

**Issue by chrisleekr** [chrisleekr/binance-trading-bot#86] opened 2021-04-09 12:36 UTC
Hey guys, 

I have worked on the features for monitoring multiple coins simultaneously #77. This change was very massive refactoring.

However, in the last few days, my purchased coins dropped dramatically and I am waiting for them for recovering. Although I think it will take forever unless the market crashed. Yes, I bought leveraged tokens for XRPDOWN and LTCDOWN, which was a very bad choice. I will never touch leveraged token once I can recover back the profit. 

Because of this reason, I haven't had trades for days because all my money is used up and locked on XRPDOWN/LTCDOWN. 

Without this change merged, I won't be able to add extra features. 

If anyone wants to monitor multiple coins simultaneously, please test this PR and let me know if there is any bug that I couldn't notice.

You can find details here:

https://github.com/chrisleekr/binance-trading-bot/pull/77#issue-608384137

Please leave any feedback to the PR.

**Comment by ggloveswp** [comment] 2021-04-09 12:51
Apart from the scope of this comment, which is obviously to provide help from people who appreciate your work and are able to test the required data, it would be a good idea to have a donation link shared, so we can give back funds that will be used either for development costs or for tests.

**Comment by chopeta** [comment] 2021-04-10 04:48
Been testing here for a few days.
Only critical bug I see is that buying price not being save.
CPU usage is much higher now but that's expected.

**Comment by wobrawu** [comment] 2021-04-10 08:56
Been testing,i found that issue:
the slack always notify "Sell Action: STOP_LOSS_LIMIT",but evently the order has not been create in the binance.

**Comment by 4KJuegos** [comment] 2021-04-10 10:22
I'm testing. For now, all is correct. Thanks for your work!

**Comment by chrisleekr** [comment] 2021-04-10 12:11
Thanks for testing, guys.

@chopeta Are you saying, the last buy price is still not saving?

**Comment by chrisleekr** [comment] 2021-04-10 12:12
@wobrawu Please see the comment https://github.com/chrisleekr/binance-trading-bot/pull/77#issuecomment-817126380

**Comment by chrisleekr** [comment] 2021-04-10 12:12
@4KJuegos Thanks for testing!

Have you made any trade? So all trades were working as expected?

**Comment by 4KJuegos** [comment] 2021-04-11 06:53
> @4KJuegos Thanks for testing!
> 
> Have you made any trade? So all trades were working as expected?

Yes, I trade VTHO and I not expected any problem. But I don't tested the Last Buy Price manually yet. All my coins was before the update. And VTHO sets automatically the Last Buy Price.

**Comment by chopeta** [comment] 2021-04-11 19:14
> Thanks for testing, guys.
> 
> @chopeta Are you saying, the last buy price is still not saving?

The bot did bought VTHO few hours ago... Last buy price not saved :-(

Let me know if there's anything I should send.

![Screenshot_20210411-141301](https://user-images.githubusercontent.com/7503721/114317961-38b20d00-9ad0-11eb-854d-bb14b6762a82.jpg)

**Comment by chopeta** [comment] 2021-04-11 19:15
On the other hand, selling seems to be working just fine.

**Comment by chopeta** [comment] 2021-04-12 03:56
I just had a couple of purchases a few minutes ago.

ONT purchase was good and last buy price was recorded.

RSR was purchased twice and last buy price was recorded.

My max. purchase was set to $200

See some screenshots...

![Screenshot_20210411-225332](https://user-images.githubusercontent.com/7503721/114338551-e517e180-9b18-11eb-9890-8509f51df8bc.jpg)

![Screenshot_20210411-225118](https://user-images.githubusercontent.com/7503721/114338603-0547a080-9b19-11eb-9bea-c14597c0a143.jpg)

![Screenshot_20210411-225131](https://user-images.githubusercontent.com/7503721/114338511-d16c7b00-9b18-11eb-9a05-9300239fd7be.jpg)

**Comment by chrisleekr** [comment] 2021-04-12 04:05
@chopeta 

Thank you so much for your testing. 

I am planning to add little more money into my account and resume actual testing.

I cannot test with the Binance test server because their Websocket price is different from the candle price. 
It's a Binance test server bug. 

>The bot did bought VTHO few hours ago... Last buy price not saved :-(

I am still not sure what is going on. The last buy price must be recorded after placing an order. :(
I will review the code again. 

> RSR was purchased twice and last buy price was recorded.

This is a good test, I mean, it's a bug, but still good to find. 
I think I can guess what is wrong with this. Once purchase the coin, it will refresh open orders immediately and account information; however, Binance API may occationally not be updated immediately. It was not happening before because it checks a few seconds later for the next tick. With this change, it checks every second and causes this unexpected behaviour. 

I have to come up with a solution to overcome this issue.

**Comment by chopeta** [comment] 2021-04-12 05:11
Someone already mentioned this... Please provide a donation address so people can help with funds. Thanks for your great work!

**Comment by chrisleekr** [comment] 2021-04-12 11:00
@chopeta 

I replicated multiple orders in the test server.

The issue I was having with the test server was, Binance test server websocket was not providing the test server's candle, but the live server's candle (which is the main reason that I could not test in the test server). 

But I found a workaround via API to retrieve current prices emulating websocket in the test server and got these multiple orders.

Let me work on the fix. Let you know how it goes. 

![image](https://user-images.githubusercontent.com/5715919/114384345-f113aa00-9bd1-11eb-8995-e6101aea87f2.png)

**Comment by chrisleekr** [comment] 2021-04-12 11:04
@chopeta 

> Someone already mentioned this... Please provide a donation address so people can help with funds. Thanks for your great work!

Thanks for trying to support the project. However, this project is related to money. As I am just "testing" my code, if I start receiving donations, it becomes pressure to me. 

I will still do my best to maintain the project as I believe in this bot. 

And I have deposited a small amount of money to test my code in the live server. :)

**Comment by chrisleekr** [comment] 2021-04-13 08:34
@chopeta 
I may take some time to write tests for the change and test to make sure it works well. 
While you wait, you can use `master` version, which works without any issue.

I am sure you already know how to do, but let me just write how to go back to master version.
```
$ git checkout master
$ docker build . --build-arg NODE_ENV=development --target dev-stage -t chrisleekr/binance-trading-bot:latest
$ docker-compose -f docker-compose.server.yml up -d
$ docker ps -a
$ docker logs binance-bot -f --tail=1000 | bunyan
```

**Comment by chopeta** [comment] 2021-04-13 10:05
Thanks for the heads up and the instructions Chris.

But I think I will stay in this version since is much faster on price update... I can live with the bugs we've found so far.

Take your time.

**Comment by chrisleekr** [comment] 2021-04-14 11:17
Hey guys, I have committed some fixes. Please read the comment and pull the latest code and test them, please.

Thanks for your participation. 

https://github.com/chrisleekr/binance-trading-bot/pull/77#issuecomment-819439986

**Comment by 4KJuegos** [comment] 2021-04-14 21:03
> Hey guys, I have committed some fixes. Please read the comment and pull the latest code and test them, please.
> 
> Thanks for your participation.
> 
> [#77 (comment)](https://github.com/chrisleekr/binance-trading-bot/pull/77#issuecomment-819439986)

Thanks! I've just updated the bot to test it.

**Comment by chopeta** [comment] 2021-04-15 05:12
Up & running with the latest version... enabling Buy action again and more pairs, many pairs :-)
Will keep you posted on the results...

**Comment by chopeta** [comment] 2021-05-01 09:30
Just did a git pull...
Still haven't tested buy/sell orders, but other bugs I had before seems to be fixed now (ie: highest price)
Much better now actually 👍 
Let's see if I can recover and spare some USDT/BUSD to test some orders.

**Comment by chrisleekr** [comment] 2021-05-01 10:59
@chopeta 
Yeah, I think it's pretty stable as I didn't get any bug report from others for few days.
I also did some trades and it worked fine without any issue.

I will wait 1 or 2 days more and will release, so I can move onto other tasks.

I may start with Stop Loss #99

**Comment by chopeta** [comment] 2021-05-03 14:06
Quick question, now with the new Global Settings the "Max purchase amount" is set per FIAT... how can we now add/remove FIAT from that list?

**Comment by chrisleekr** [comment] 2021-05-03 22:07
@chopeta The max purchase amount field for new FIAT will automatically add to UI if you add it to the symbol list.
For example, if you didn't have XRPBUSD before and added to the symbol, then it should appear Max purchase amount for BUSD. :)

**Comment by starush** [comment] 2021-05-06 20:44
Added about 10 pairs with BUSD and then removed all USDT pairs at web frontend. after several minutes of use the webpage became empty. When reloading, it shows just the title (and nothing else) for half of second, then empty page again. I guess maybe reason in massive quantity of BUSD pairs. How can I restore the default settings?

**Comment by xFeliXx** [comment] 2021-05-12 23:35
For the past few days I have used the changes until [this](https://github.com/chrisleekr/binance-trading-bot/pull/77/commits/60b66206f624f3cfc7ea4fbce77c1d64adc0a2c6) commit, and I've noticed these issues:
- One time I've noticed that last buy price wasn't recorded and left with "N/A", here are the logs from Slack around that time:
```
LTCUSDT Buy Action (22:39:57.181): STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "LTCUSDT",
  "side": "buy",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 0.04401,
  "stopPrice": 340.08,
  "price": 340.42,
  "timeInForce": "GTC"
}
```
```
LTCUSDT Buy Action Result (22:39:58.157): STOP_LOSS_LIMIT
   - Order Result:
{
  "symbol": "LTCUSDT",
  "orderId": 1762905249,
  "orderListId": -1,
  "clientOrderId": "KzhYfob6rzLpyLihMli20y",
  "transactTime": 1620859197371
}
```
```
LTCUSDT Action (22:39:59.526): Checking for buy order
- Message: The buy order cannot be found in the open orders.
{
  "lastBuyOrder": {
    "symbol": "LTCUSDT",
    "orderId": 1762905249,
    "orderListId": -1,
    "clientOrderId": "KzhYfob6rzLpyLihMli20y",
    "transactTime": 1620859197371
  },
  "openOrders": []
}
```
```
LTCUSDT Action (22:40:00.622): Checking for buy order
- Message: The buy order cannot be found in the open orders.
{
  "lastBuyOrder": {
    "symbol": "LTCUSDT",
    "orderId": 1762905249,
    "orderListId": -1,
    "clientOrderId": "KzhYfob6rzLpyLihMli20y",
    "transactTime": 1620859197371
  },
  "openOrders": []
}
```
```
LTCUSDT Action (22:40:01.467): Checking for buy order
- Message: The buy order cannot be found in the open orders.
{
  "lastBuyOrder": {
    "symbol": "LTCUSDT",
    "orderId": 1762905249,
    "orderListId": -1,
    "clientOrderId": "KzhYfob6rzLpyLihMli20y",
    "transactTime": 1620859197371
  },
  "openOrders": []
}
```
```
LTCUSDT Action (22:40:03.008): Confirmed buy order
- Message: The buy order found in the open orders.
{
  "lastBuyOrder": {
    "symbol": "LTCUSDT",
    "orderId": 1762905249,
    "orderListId": -1,
    "clientOrderId": "KzhYfob6rzLpyLihMli20y",
    "transactTime": 1620859197371
  },
  "openOrders": [
    {
      "symbol": "LTCUSDT",
      "orderId": 1762905249,
      "orderListId": -1,
      "clientOrderId": "KzhYfob6rzLpyLihMli20y",
      "price": "340.42000000",
      "origQty": "0.04401000",
      "executedQty": "0.00000000",
      "cummulativeQuoteQty": "0.00000000",
      "status": "NEW",
      "timeInForce": "GTC",
      "type": "STOP_LOSS_LIMIT",
      "side": "BUY",
      "stopPrice": "340.08000000",
      "icebergQty": "0.00000000",
      "time": 1620859197371,
      "updateTime": 1620859197371,
      "isWorking": false,
      "origQuoteOrderQty": "0.00000000"
    }
  ]
}
```
```
LTCUSDT Action (22:40:11.750): Removed last buy price
- Message: Balance is not enough to sell. Delete last buy price.
{
  "lastBuyPrice": 340.42,
  "baseAssetQuantity": 0,
  "minQty": "0.00001000",
  "baseAssetFreeBalance": 0,
  "baseAssetLockedBalance": 0,
  "totalBaseAssetBalance": 0,
  "openOrders": []
}
```
The balance seemed to be enough to sell, and only after I entered last buy price manually, the bot started to monitor the sell signal.
Maybe I'm missing something?
- Sometimes non existant open buy orders were shown. UI was switching back and forth between them even though only one buy order was open and active. I've observed such behaviour for at least half an hour after the latest fullfilled buy order.
- Buy order is still appearing sometimes even though it was fulfilled half an hour ago (probably related to previous point):
![image](https://user-images.githubusercontent.com/1419306/118055048-0aa24000-b390-11eb-84df-2f84bb4a6213.png)
![image](https://user-images.githubusercontent.com/1419306/118055077-1aba1f80-b390-11eb-8139-126256adbbdd.png)

I'll pull the latest commits and will check if anything changes.

**Comment by chrisleekr** [comment] 2021-05-14 02:48
@xFeliXx 

> 1) One time I've noticed that last buy price wasn't recorded and left with "N/A", here are the logs from Slack around that time:

 Hey, I had a similar issue today in the morning. Very similar to your case.

Your log:
```
22:39:57.181 Buy order
22:39:58.157 Buy order result
22:39:59.526 Cannot find buy order
22:40:00.622 Cannot find buy order
22:40:01.467 Cannot find buy order
22:40:03.008 Found order
22:40:11.750 Removed last buy price
```

My log:
```
- 17:30:48:067 Buy
- 17:30:48:671 Buy Result
- 17:30:49.237 Cannot find from open order
- 17:30:50.437 Cannot find from open order
- 17:30:51.441 Cannot find from open order
- 17:30:52.463 Cannot find from open order
- 17:30:53.287 Cannot find from open order
- 17:30:54.237 Cannot find from open order
- 17:30:55.432 Found from open order
- 17:31:05.319 Removed last buy price
- 17:40 Order fulfilled

```

It's definitely Binance API issue that is not returning open orders. I am preparing a new commit to not refresh open orders in `trailingTradeIndicator` for 1 min, which gives some cool time to API.

> 2) Sometimes non existant open buy orders were shown. UI was switching back and forth between them even though only one buy order was open and active. I've observed such behaviour for at least half an hour after the latest fullfilled buy order.
> 3) Buy order is still appearing sometimes even though it was fulfilled half an hour ago (probably related to previous point):
> 4) After update and container restart, wrong current price was fetched, which also removed last buy price:

I think this issue https://github.com/chrisleekr/binance-trading-bot/issues/144#issuecomment-831854610  is similar to your situation, which I fixed with the latest commit. What version are you running? You can see from the bottom of the front end. Even if you pulled the latest commit, you still need to build a docker image as it's in development. 

![image](https://user-images.githubusercontent.com/5715919/118213513-729c7780-b4b1-11eb-8f01-220d53ecf5b4.png)

Issues 2,3,4 are all related to the bot was not updating in the background.
Make sure the frontend showing the correct commit hash.

**Comment by xFeliXx** [comment] 2021-05-14 10:04
@chrisleekr 

> I think this issue #144 (comment) is similar to your situation, which I fixed with the latest commit. What version are you running? You can see from the bottom of the front end. Even if you pulled the latest commit, you still need to build a docker image as it's in development.

Currently, at the bottom of the page, it says:
```
Running Version: v0.0.65 (unspecified)
```

When I pulled the latest commits I made sure that the container was re-created, but I didn't manually re-build it, maybe that was the cause. I've re-built it now, will see how it goes.

Thanks for your work!

**Comment by chrisleekr** [comment] 2021-05-14 10:50
@xFeliXx 

If it said `unspecified`, you seem running `docker-compose.yml`.

Try to do 

```
$ npm run docker:build
$ docker-compose -f docker-compose.server.yml up -d
```

That will give you a production image, rather than a development image.

**Comment by xFeliXx** [comment] 2021-05-14 13:00
@chrisleekr 

I'm running `docker-compose.server.yml` but I've slightly modified it.

I think that your proposal won't work because `docker-compose.server.yml` currently points to an outdated docker hub image. 
It will always try to take that image instead of the currently built one.

Here is how I changed it before running a custom branch:
```
 services:
   binance-bot:
     container_name: binance-bot
-    image: chrisleekr/binance-trading-bot:latest
+    build: .
     networks:
       - internal
     env_file:
```

It probably displays `unspecified` because I'm building with `docker-compose`, and the package version is not specified there during build.

**Comment by chrisleekr** [comment] 2021-05-14 13:02
@xFeliXx 

It won't use DockerHub's docker image if you run this command:

```
$ npm run docker:build
```

Unless you are developing, you don't need to use `docker-compose.yml`.

**Comment by chrisleekr** [comment] 2021-05-14 15:25
@xFeliXx

I have pushed a new commit to disable actions after placing an order for 20 seconds and prevent removing the last buy price.

I am still testing the changes, wait for buy/sell in my bot. 

See how it goes.

**Comment by chrisleekr** [comment] 2021-05-15 01:09
Guys, please refer https://github.com/chrisleekr/binance-trading-bot/pull/77#issuecomment-841576418

**Comment by xFeliXx** [comment] 2021-05-15 11:26
> The above command will build the new image in your local and when you launch docker-compose.server.yml, it will use your local image.

Yeah, you're right.

> I have pushed a new commit to disable actions after placing an order for 20 seconds and prevent removing the last buy price.
I am still testing the changes, wait for buy/sell in my bot.
See how it goes.

Ok, thanks, I'll update and test as well.

**Comment by chrisleekr** [comment] 2021-05-16 06:19
Refer https://github.com/chrisleekr/binance-trading-bot/pull/77#issuecomment-841775318

**Closed** 2021-05-21 12:53 UTC
Labels: help wanted
