### ISSUE TITLE
Unable to sell 100%, it will always leave the smallest unit like 0.001, which will not be sold.(Translated by Google )

### ISSUE THREAD

**Issue by miteasy** [chrisleekr/binance-trading-bot#402] opened 2021-12-21 05:58 UTC
![WX20211221-134750](https://user-images.githubusercontent.com/18578249/146878218-2b388707-7967-4110-ad6e-27924076a2b6.png)

I have set the sell quantity percentage to 1.
No matter what symbol or amount I trade, this will always happen.

**Comment by caebwallace** [comment] 2021-12-21 09:48
Not a bug, it's due to decimals allowed by binance for orders and called "dust".
You can convert dust token to BNB by using "convert small balance to BNB" link, in the "Account Balance" zone.

**Comment by ilbuonmarcio** [comment] 2021-12-29 16:31
It's not a bug, it's a technical limitation of the coins itself.
The only solution is to convert small balance to BNB, as @caebwallace suggested

**Comment by ilbuonmarcio** [comment] 2021-12-29 16:32
If you can, please close this issue, thanks.

**Closed** 2021-12-30 03:54 UTC
Labels: bug
