### ISSUE TITLE
High CPU usage on docker

### ISSUE THREAD

**Issue by rayures** [chrisleekr/binance-trading-bot#262] opened 2021-08-02 09:27 UTC
## Version
latest docker 
chrisleekr/binance-trading-bot:latest@sha256:d79e5410e42884eee835f652fb78c8c7c5bbe814bad3967057cd6d5f5ed96ce5

Running Version: v0.0.74 (67a4adf)
Latest Version:
v0.0.74

## Description
the binance trade bot docker container is continuously using 30-40 % cpu time. (top in host, and docker stats on host). Host is a 4 core i5 machine. No limits on the container. 

host:
  i5 4c
  Operating System: Debian GNU/Linux 10 (buster)
  Kernel: Linux 4.19.0-17-amd64
  Architecture: x86-64
docker:
  Docker version 19.03.5, build 633a0ea838

docker stats:
![image](https://user-images.githubusercontent.com/5716188/127838350-348d1642-4f32-41da-b214-46d8e47824c9.png)

in the binance bot container:
![image](https://user-images.githubusercontent.com/5716188/127838158-0832386b-a8ec-4f86-a4a2-ca4f25b255fa.png)

is this normal behavior?

**Comment by habibalkhabbaz** [comment] 2021-08-02 10:04
I have high RAM usage problem with Docker after running the bot for couple of hours.
However, I don't think the issue is related to the bot but it is related to the Docker instead as many people complaining about high usage problem using Docker.
I tried to apply limits using WSL in Windows but no luck, still it is behaving strange when it's reached the maximum allowed value and my PC being heavy.
I am still trying to find a solution for this 🙅‍♂️

**Comment by pedrohusky** [comment] 2021-08-02 11:10
> I am having high RAM usage with Docker after running the bot for couple of hours.
> However, I don't think the issue is related to the bot but it is related to the Docker instead as many people complaining about high usage problem using Docker.
> I tried to apply limits using WSL in Windows but no luck, still it is behaving strange when it's reached the maximum allowed value and my PC being heavy.
> I am still trying to find a solution for this 🙅‍♂️ 

Maybe there is a way for us to not use docker?

Like, start the bot right from terminal?

**Comment by chrisleekr** [comment] 2021-08-02 11:14
@rayures 

The bot running in RPi4 uses 30~40% CPU as well, which makes sense since it's so low spec.

But the bot running in i5/8GB Ubuntu server(18 Bionic Feaver) running 4~10% CPU only. 

It seems you are using Ubuntu 10 (Buster), which is very old. Is there any specific reason that you are using that version?

> Like, start the bot right from terminal?

If you install redis/mongo separately, it is definitely possible, but I don't think that will benefit anyway because Docker itself uses native resources.

**Comment by habibalkhabbaz** [comment] 2021-08-02 11:16
> > I am having high RAM usage with Docker after running the bot for couple of hours.
> > However, I don't think the issue is related to the bot but it is related to the Docker instead as many people complaining about high usage problem using Docker.
> > I tried to apply limits using WSL in Windows but no luck, still it is behaving strange when it's reached the maximum allowed value and my PC being heavy.
> > I am still trying to find a solution for this 🙅‍♂️
> 
> Maybe there is a way for us to not use docker?
> 
> Like, start the bot right from terminal?

Yes, there is a way for this but the problem is we have to install everything separately, such as mongodb and redis on our local OS. That's why I prefer Docker.
I am thinking of installing Ubuntu on my PC but no space xD

**Comment by pedrohusky** [comment] 2021-08-02 11:19
> > Like, start the bot right from terminal?
> 
> If you install redis/mongo separately, it is definitely possible, but I don't think that will benefit anyway because Docker itself uses native resources.
> 

Hm. Can you explain me how to do it? I would like to test it without the docker, as my machine has low ram (8gb), and docker eats it all.

I think this will fix many problems, like:

- Clock desync, that is a constant problem.
- Memory/CPU will not be abused.
- Even the changes in the project will be better with the terminal, as it is faster than docker in any way.

But, as you said, docker manages it all, and it is compatible to multiple systems.

But I think it will benefit us.

**Comment by chrisleekr** [comment] 2021-08-02 11:23
@pedrohusky 
I do not have Windows machine so I cannot tell how exactly.

Briefly, install Redis, Mongo.
Simply point them by updating config.
- https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json#L14

**Comment by rayures** [comment] 2021-08-02 11:32
> 
> 
> @rayures
> 
> The bot running in RPi4 uses 30~40% CPU as well, which makes sense since it's so low spec.
> 
> But the bot running in i5/8GB Ubuntu server(18 Bionic Feaver) running 4~10% CPU only.
> 
> It seems you are using Ubuntu 10 (Buster), which is very old. Is there any specific reason that you are using that version?

cat /etc/debian_version
10.10

its Debian at its latest version.... Why do you think its old?

**Comment by chrisleekr** [comment] 2021-08-02 11:33
Oh sorry, I thought it's Ubuntu.... Ubuntu Buster was v10.

**Comment by rayures** [comment] 2021-08-02 13:15
upgraded Debian 10.10 to 11.0
upgraded Docker 19.03.5 to 20.10.7

still high cpu load (about 40%).

**Comment by vuongductuanktmt** [comment] 2021-08-09 13:50
Same issue please fix it. Thanks sir
![2021-08-09_05-33-28](https://user-images.githubusercontent.com/25997663/128716874-33d4fdc3-bc31-4cfa-8b53-1a9915b02cce.png)
****

**Comment by chrisleekr** [comment] 2021-08-09 13:55
@rayures  Sorry for the late reply.
The main change in that release is `Support monitoring multiple coins simultaneously - #77`, which actively checks the multiple symbols.

@vuongductuanktmt 
I don't think I can fix it. There must be something else is going on.

My latest version in RPi is not even using 50%.

![image](https://user-images.githubusercontent.com/5715919/128717628-6795c18c-b968-4899-a74d-c1b7ac6df22e.png)
![image](https://user-images.githubusercontent.com/5715919/128717740-f624097d-d482-4b41-827e-e4295804b4ba.png)

**Comment by bangbaew** [comment] 2021-08-10 08:51
> @rayures Sorry for the late reply.
> The main change in that release is `Support monitoring multiple coins simultaneously - #77`, which actively checks the multiple symbols.
> 
> @vuongductuanktmt
> I don't think I can fix it. There must be something else is going on.
> 
> My latest version in RPi is not even using 50%.
> 
> ![image](https://user-images.githubusercontent.com/5715919/128717628-6795c18c-b968-4899-a74d-c1b7ac6df22e.png)
> ![image](https://user-images.githubusercontent.com/5715919/128717740-f624097d-d482-4b41-827e-e4295804b4ba.png)

I'm also using RPi 4 with latest bot version (0.0.74), same OS as yours
![image](https://user-images.githubusercontent.com/29559559/128836452-a18dedcd-323a-4a33-bf25-70e5f1384ad0.png)

but the container constantly exits and restarts itself, looks like the CPU is being excessively used
![Screen Shot 2564-08-10 at 15 34 57](https://user-images.githubusercontent.com/29559559/128836589-4f805659-500b-4484-abaf-73e4a67923ae.png)

From my Grafana monitor, you can see that the temperature is constantly getting up (around 40c), this is when the container is running, and down (around 35c), this is when the container is exiting and trying to restart, the Grafana is also slow to visit, I'm not sure if it's Docker problem, what should I do to fix it?

![image](https://user-images.githubusercontent.com/29559559/128837274-3cfba029-83a7-43af-bb84-608d604e7c4b.png)

looks like it's using excessive cpu in **docker stats**
![image](https://user-images.githubusercontent.com/29559559/128837605-dbf1056f-8f8e-4737-b4b7-cd9bd803bf05.png)

**Comment by chrisleekr** [comment] 2021-08-10 08:54
Hey @bangbaew 

Can you try with disabling swap?

https://chrislee.kr/wp/2021/04/26/disable-swap-in-raspberry-pi/

**Comment by bangbaew** [comment] 2021-08-10 08:56
> Hey @bangbaew
> 
> Can you try with disabling swap?
> 
> 1. sudo nano /etc/dphys-swapfile
> 2. change CONF_SWAPSIZE=0
> 3. Save and Reboot

Ok, I'll try it and give you an update,
but in my comment I attached the wrong **docker stats** picture.
I was meant to attach this picture
![image](https://user-images.githubusercontent.com/29559559/128838350-392dfed2-cd22-441c-93aa-01c56d5a95b0.png)

**Comment by chrisleekr** [comment] 2021-08-10 08:59
Compare with mine.

![image](https://user-images.githubusercontent.com/5715919/128838716-f9bf30a0-d365-45de-8b24-5a655ccc9274.png)
 
Disable swap may help to release block I/O.

**Comment by bangbaew** [comment] 2021-08-10 09:49
> Compare with mine.
> 
> ![image](https://user-images.githubusercontent.com/5715919/128838716-f9bf30a0-d365-45de-8b24-5a655ccc9274.png)
> 
> Disable swap may help to release block I/O.

Looks like the bot is still exiting and restarting...
![Screen Shot 2564-08-10 at 16 36 57](https://user-images.githubusercontent.com/29559559/128844872-0d8ee231-beef-43fa-8aec-7cff4ed387c8.png)

even I've disabled swapfile and block i/o is 0 bytes
![image](https://user-images.githubusercontent.com/29559559/128844854-6bdea9f8-78c2-4f28-8969-0f674686f431.png)

My RPi was really slow before the container exited.
what build stage are you using? I'm currently using the full production build stage.

This is my compose file, I saw it was using development build stage with binance test mode when I downloaded it,
so I changed to production stage with live mode.
[docker-compose.yml.zip](https://github.com/chrisleekr/binance-trading-bot/files/6960648/docker-compose.yml.zip)

**Comment by chrisleekr** [comment] 2021-08-10 10:20
Hmmm, I don't know why are you running docker-compose.yml. 
As I instructed in the README.md, use this method.

```
Or if using Raspberry Pi 4 32bit, must build again for Raspberry Pi:

npm run docker:build
docker-compose -f docker-compose.rpi.yml up -d
```

FYI, I found it looks stuck at building step, but it is not, takes really long time to build.

What I am trying to do is to distribute docker image for ARM/v7, which is RPi, then you won't need to build the image. Just need docker image.

**Comment by chrisleekr** [comment] 2021-08-10 10:20
And for the restarting, have you looked at the log?

https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by bangbaew** [comment] 2021-08-10 10:31
> Hmmm, I don't know why are you running docker-compose.yml.
> As I instructed in the README.md, use this method.
> 
> ```
> Or if using Raspberry Pi 4 32bit, must build again for Raspberry Pi:
> 
> npm run docker:build
> docker-compose -f docker-compose.rpi.yml up -d
> ```
> 
> FYI, I found it looks stuck at building step, but it is not, takes really long time to build.
> 
> What I am trying to do is to distribute docker image for ARM/v7, which is RPi, then you won't need to build the image. Just need docker image.

Because I used **docker-compose.rpi.yml** and it pulled your image from the docker hub which was build for x86 and it ended up with **standard_init_linux.go:219: exec user process caused: exec format error** like this thread
https://github.com/perara/wg-manager/issues/69

but I didn't understand the **npm run docker:build** command so I didn't run it, I thought it was like normal Dockerfile building, so I used **build: .** instead, it didn't stuck but it just took a quite long time to build.

I'll try to **use npm run docker:build**

**Comment by bangbaew** [comment] 2021-08-10 12:01
> I'll try to use **npm run docker:build**

I've tried **npm run docker:build**, I think it's the same as normal Dockerfile building as I usually do, the container was still crashing, I think the problem is with monitoring symbols every second, which consumes a lot of cpu, because I had more than 30 symbols monitoring and the timer took a long time to refresh before crashing, so I cleaned the volumes to default 4 symbols monitored, the bot works smoothly, the timer increases second by second without crashing.

Can you add the option to adjust monitoring interval? I think it could be monitored every minute like the bot before monitoring-coins-simultaneously release. my RPi worked great with that version.

**Comment by chrisleekr** [comment] 2021-08-10 12:06
I really don't think it's the issue with the bot because I use it without much hassle.

What SD card are you using? Are you using 10 Speed Class?

![image](https://user-images.githubusercontent.com/5715919/128863677-6b7dd1f8-ddad-46eb-b762-318ecad465a4.png)


Crashing is not making sense as well. Have you checked the log? What did the log say when it's crashed?

In anyway, if you want to increase interval, refer these environments parameters you can set.

https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json#L86
https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json#L213

**Comment by bangbaew** [comment] 2021-08-10 12:19
> I really don't think it's the issue with the bot because I use it without much hassle.
> 
> What SD card are you using? Are you using 10 Speed Class?
> 
> ![image](https://user-images.githubusercontent.com/5715919/128864556-686afe1d-5acf-402a-84b6-21ae95cb2890.png)
> (Updated: image for sd card was not micro sd card.)
> 
> Crashing is not making sense as well. Have you checked the log? What did the log say when it's crashed?
> 
> In anyway, if you want to increase interval, refer these environments parameters you can set.
> 
> https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json#L86
> https://github.com/chrisleekr/binance-trading-bot/blob/master/config/custom-environment-variables.json#L213

The log didn't say error messages, they were just normal bot messages log but it was so slow logging and eventually crashed so I didn't capture any screenshot of it, my SD card is SanDisk class 10 UHS-I
![image](https://user-images.githubusercontent.com/29559559/128865280-00696fc9-436a-43c4-929f-3c3d428c176f.png)

thanks for suggesting me the environment variable, may I ask what's the unit of it? seconds?

**Comment by chrisleekr** [comment] 2021-08-10 12:21
The variable values can be referred in this file - https://github.com/chrisleekr/binance-trading-bot/blob/master/config/default.json#L50

It's crontab with milliseconds.

**Comment by rayures** [comment] 2021-08-10 14:48
thnx for the reply. 

as a test i increased the delay in the default config ( crontime  ) to double the amount. Can see it directly in cpu usage. Switching between 2% and 40%. So it definitely is the coin updates.

**Comment by bangbaew** [comment] 2021-08-11 04:02
> The variable values can be referred in this file - https://github.com/chrisleekr/binance-trading-bot/blob/master/config/default.json#L50
> 
> It's crontab with milliseconds.

I've set **BINANCE_JOBS_TRAILING_TRADE_CRON_TIME=*/10 * * * * ***
it refreshes every 10 seconds and it now consumes much lower cpu usage!,
but I don't quite understand what **BINANCE_JOBS_TRAILING_TRADE_INDICATOR_CRON_TIME** does,
can you please explain?,
thanks.

**Comment by chrisleekr** [comment] 2021-08-11 13:50
@bangbaew 

As I said, this cronjob is supporting seconds as well. So it's 6 *, which means every second.
`* * * * * *`

If you set `*/10 * * * * *`, it will run every 10 seconds.

`BINANCE_JOBS_TRAILING_TRADE_INDICATOR_CRON_TIME` is another cronjob which requires for operating the bot.
See this file to understand how it works - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTradeIndicator/steps.js

**Comment by vuongductuanktmt** [comment] 2021-08-14 15:52
bot doesn't work like the time frame on the photo below, I checked the current prices of the coins and didn't see any updates. I had to restart and the bot worked fine. thanks sir

![image](https://user-images.githubusercontent.com/25997663/129451877-ca1e571f-2a2e-4829-b0be-7f8f1da9dbd0.png)

**Comment by bangbaew** [comment] 2021-08-14 16:02
> bot doesn't work like the time frame on the photo below, I checked the current prices of the coins and didn't see any updates. I had to restart and the bot worked fine.
> I had to use crontab every 8 hours to restart the bot to solve this problem, do you have a better solution.
> 
> Thanks sir
> 
> ![image](https://user-images.githubusercontent.com/25997663/129451877-ca1e571f-2a2e-4829-b0be-7f8f1da9dbd0.png)

Do you have 30++ symbols monitored simultaneously every second? It's really consuming the CPU.
I also had the same problem, so I have to increase the monitoring time to every 10 seconds and now it works flawlessly.

**Comment by vuongductuanktmt** [comment] 2021-08-14 16:23
> > bot doesn't work like the time frame on the photo below, I checked the current prices of the coins and didn't see any updates. I had to restart and the bot worked fine.
> > I had to use crontab every 8 hours to restart the bot to solve this problem, do you have a better solution.
> > Thanks sir
> > ![image](https://user-images.githubusercontent.com/25997663/129451877-ca1e571f-2a2e-4829-b0be-7f8f1da9dbd0.png)
> 
> Do you have 30++ symbols monitored simultaneously every second? It's really consuming the CPU.
> I also had the same problem, so I have to increase the monitoring time to every 10 seconds and now it works flawlessly.

set BINANCE JOBS TRAILING TRADE_INDICATOR_CRON_TIME = * / 10 * * * * * * in the .env file correct sir?

**Comment by chrisleekr** [comment] 2021-08-15 02:25
@vuongductuanktmt 

> I had to use crontab every 8 hours to restart the bot to solve this problem, do you have a better solution.

I also restart the bot every 3 hours in Raspberry Pi, but it's not because of the performance. I do that because of the local tunnel.
I will check the code and try to improve the performance, but not sure whether it's possible. :man_shrugging:

**Comment by chrisleekr** [comment] 2021-08-23 11:36
Hey, 

Can you check the redis log whether you see the below message?


```
$ docker logs binance-redis -f

...
2956:C 23 Aug 2021 11:29:03.109 * RDB: 0 MB of memory used by copy-on-write
1:M 23 Aug 2021 11:29:03.164 * Background saving terminated with success
1:M 23 Aug 2021 11:29:13.009 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
1:M 23 Aug 2021 11:29:15.011 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
1:M 23 Aug 2021 11:30:04.067 * 10000 changes in 60 seconds. Saving...
...
```

**Comment by rayures** [comment] 2021-08-23 12:04
currently i am running pedrohusky fork, that one runs about 1% cpu (all containers combined). Will try to switch back and look at the redis log.

**Comment by vuongductuanktmt** [comment] 2021-08-23 16:09
> Hey,
> 
> Can you check the redis log whether you see the below message?
> 
> ```
> $ docker logs binance-redis -f
> 
> ...
> 2956:C 23 Aug 2021 11:29:03.109 * RDB: 0 MB of memory used by copy-on-write
> 1:M 23 Aug 2021 11:29:03.164 * Background saving terminated with success
> 1:M 23 Aug 2021 11:29:13.009 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
> 1:M 23 Aug 2021 11:29:15.011 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
> 1:M 23 Aug 2021 11:30:04.067 * 10000 changes in 60 seconds. Saving...
> ...
> ```

```
4200:C 19 Aug 2021 23:27:07.883 * RDB: 0 MB of memory used by copy-on-write
1:M 19 Aug 2021 23:27:07.965 * Background saving terminated with success
1:M 19 Aug 2021 23:28:26.076 * 10000 changes in 60 seconds. Saving...
1:M 19 Aug 2021 23:28:26.078 * Background saving started by pid 4201
4201:C 19 Aug 2021 23:28:26.144 * DB saved on disk
```

**Comment by chrisleekr** [comment] 2021-08-28 04:01
What I found is, Redis is trying to save the changes to the disk so it doesn't lose the data. It's called AOF.

```
1:M 19 Aug 2021 23:18:08.000 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
```

Since Raspberry Pi is not using SSD or a faster disk, it causes a bottleneck.

A Redis is just a temporary cache, it should be able to flush anytime. 
However, some features in the bot are relying on the Redis to be persistent.

I am testing the code with the following changes:

```
- Added indexes for MongoDB
- Updated configuration to use cache as well to improve performance
- Updated redis.conf to disable AOF for improving performance
- Moved grid/manual orders to MongoDB from Redis since Redis is not persistent anymore
```

Although it's not improving performance in the Raspberry Pi significantly since it still requires read/write to MongoDB for some features. However, at least Redis would not write to the disk anymore as it shouldn't be.

**Comment by chrisleekr** [comment] 2021-11-09 10:18
I assume this is no longer the issue. I will close the issue.

**Closed by chrisleekr** 2021-11-09 10:18 UTC
Labels: question
