### ISSUE TITLE
Doubled or missing sell orders since websocket implemented

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#451] opened 2022-07-29 20:50 UTC
## Version

v0.0.88 (9c2e4f5)

## Description

In radnom appearance there are single sell orders counted as two sell orders at once. There is single sell order executed on Binance side resulted into two closed trade records on bot side. This is doubling calculated profitability.

In random appearance there are closed trades executed on Binance side triggering removing last buy price without accounting last sell order thus removing trade grid with calculated 100% loss. This is worsening calculated profitability.

## To Reproduce

There are no actual steps to reproduce as the bug is appearing randomly.

## Expected Behaviours

Single sell order should be counted as single transaction in closed trades history.

## Screenshots

Doubled sell order:
![image](https://user-images.githubusercontent.com/37454226/181840693-e5331225-be7e-48a8-97af-0d287453bef9.png)

Missing sell order:
![image](https://user-images.githubusercontent.com/37454226/181841330-fe50ed48-def5-472d-a12c-195ff53a6782.png)

**Comment by habibalkhabbaz** [comment] 2022-07-29 21:11
Hello @uhliksk 
I didn't face this issue but I can imagine how this can happen.

WebSocket is fast and we are calling `executeTrailingTrade` for each ticker received. This can trigger `executeTrailingTrade` two times in a short time so that's why the action can be duplicated.

### My suggested solution
Use queue for each symbol to queue the calls of `executeTrailingTrade`

This is the same for #450

**Comment by uhliksk** [comment] 2022-07-29 21:44
Hello @habibalkhabbaz

That's great you found a possible vector of fail. Do you think it will solve also the missing sell orders problem? I didn't catched a log for both incidents as they happend more than 30 minutes ago but I'll try to monitor the bot more frequently to catch how exactly it's been processed.

**Comment by habibalkhabbaz** [comment] 2022-07-29 23:21
@uhliksk 

I think that's another issue.

I have two question:

1. What is your `Last buy price removal threshold` ?
2. The sell order was initiated from bot or from Binance directly ?

**Comment by uhliksk** [comment] 2022-07-30 18:21
@habibalkhabbaz 

1. Last buy price removal threshold is 10 BUSD
2. The sell order was initiated from bot

Today I even found tripple buy order in Order History executed by bot:

![image](https://user-images.githubusercontent.com/37454226/181936238-6d4d2aeb-9978-460f-b4a8-320068b13353.png)

I'll try today to migrate the bot to another server with higher performance to see if cpu bottleneck is the issue. Right now it's using 80% of single core.

![image](https://user-images.githubusercontent.com/37454226/181936402-39f14311-fea7-4b2d-bb2e-e67a7369fc25.png)

**Comment by Rayn0r** [comment] 2022-07-30 19:12
I have seen double orders in 0.0.85 before. It usually happened when the bot was trying to cancel an already placed order because its price had changed. 
So the second order got executed because the bot had not noticed, that the first one had not been canceled. 
This way the same grid order got executed twice.

**Comment by uhliksk** [comment] 2022-07-30 19:30
@Rayn0r This is something else as those duplicate orders are created at once.

**Comment by uhliksk** [comment] 2022-07-31 13:17
@habibalkhabbaz I implemented `executeTrailingTrade` queueing which resulted in much smaller log clearly indicating function is called less times than with original code. CPU usage also dropped and I haven't seen duplicate orders yet. I'll try running the current code longer to be sure everything is working well. On my original "low performance" server CPU usage dropped from 80% to about 40% on average.

![image](https://user-images.githubusercontent.com/37454226/182028169-bd626f15-9ad7-4a02-b4e6-c8bd8ce87215.png)

**Comment by habibalkhabbaz** [comment] 2022-07-31 13:39
> @habibalkhabbaz I implemented `executeTrailingTrade` queueing which resulted in much smaller log clearly indicating function is called less times than with original code. CPU usage also dropped and I haven't seen duplicate orders yet. I'll try running the current code longer to be sure everything is working well. On my original "low performance" server CPU usage dropped from 80% to about 40% on average.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37454226/182028169-bd626f15-9ad7-4a02-b4e6-c8bd8ce87215.png)
> 
> 

Hey @uhliksk 

That's great.
Today I was thinking of this and I came up with a better solution instead of queuing. Queuing the execution may result a delayed execution and we don't want this to happen.

### The new suggested solution

1. Cache a value when execution just started for a symbol 
2. Remove this value at the end of execution
3. Check if this value is set at the top of `executionTrailingTrade`

### Sample code

```
if (cached value is already set for a symbol) {
 // do nothing because there is uncompleted execution before
 return;
}

// cache the value here

.....steps of execution

// reset cache here
```

I can create PR to implement this if you like or you can do it as well.

Or if you like we may include the fixes in my last PR since it is made for error handling and improve stability.

**Comment by habibalkhabbaz** [comment] 2022-07-31 15:10
@uhliksk 
Done. I pushed a fix for this.

**Comment by uhliksk** [comment] 2022-07-31 16:28
@habibalkhabbaz Great. But I think it'll be even better to not just `return` when execution task is already running but set a flag in cache to indicate there is a skipped attempt to execute and check for this flag at the end of execution. If flag is set then you should reexecute processing again until there is a clear flag. This way missed attempts will not be delayed until an another change is received, but they will be processed asap.

**Comment by habibalkhabbaz** [comment] 2022-07-31 16:39
@uhliksk 
Nice idea!
However, re-execute the failed attempt may lead to unexpected result. 

WebSocket send updates every 1 second for a symbol. That means the `executeTrailingTrade` will be called every 1 second (if the symbol is very active)
So I think we can simply discard the attempt as I did because we will receive another tick within 1 second and `executeTrailingTrade` will be called again.

**Comment by uhliksk** [comment] 2022-07-31 16:45
@habibalkhabbaz From what I've seen if there is no change in a symbol then `executeTrailingTrade` is not called for even a minutes. I think it's better to not wait until next call is fired by WebSocket.

**Comment by uhliksk** [comment] 2022-07-31 16:49
@habibalkhabbaz Right now I have UNIBUSD not updated for 29 seconds. If there was skipped call with your solution then it will be not processed for those full 29 seconds (and maybe longer).

![image](https://user-images.githubusercontent.com/37454226/182036768-895187ca-a60c-42f6-b028-871e2de59ad4.png)

**Comment by uhliksk** [comment] 2022-07-31 17:49
@habibalkhabbaz Bad news. Missing sell order bug is still not fixed.

![image](https://user-images.githubusercontent.com/37454226/182038847-cd9c1e5a-01f4-4d33-adee-8d302e35d47e.png)

Unfortunately I had logging turned off as I thought the problem is finally solved.

**Comment by habibalkhabbaz** [comment] 2022-07-31 17:55
> @habibalkhabbaz Right now I have UNIBUSD not updated for 29 seconds. If there was skipped call with your solution then it will be not processed for those full 29 seconds (and maybe longer).
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37454226/182036768-895187ca-a60c-42f6-b028-871e2de59ad4.png)

I understood!
Let me think for an improvement for this.

**Comment by habibalkhabbaz** [comment] 2022-07-31 17:56
> @habibalkhabbaz Bad news. Missing sell order bug is still not fixed.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37454226/182038847-cd9c1e5a-01f4-4d33-adee-8d302e35d47e.png)
> 
> 
> 
> Unfortunately I had logging turned off as I thought the problem is finally solved.

Ohh.
Do you use my last PR or your own implemented queue?

**Comment by uhliksk** [comment] 2022-07-31 18:09
> Ohh. Do you use my last PR or your own implemented queue?

I used my own implemented queue which is even safer than skipping the calls. It's possible those cancelled orders will cancel this final executed sell order when processed?

![image](https://user-images.githubusercontent.com/37454226/182039565-f436b19d-b138-4a2e-a2b8-cefb5493aa34.png)

**Comment by habibalkhabbaz** [comment] 2022-07-31 18:26
@uhliksk 

I am sure about the duplicated orders which is solved now and it needs only minor improvement as per your feedback. However, the lost sell order as I said it's another issue. So, let me debug this.

I remember I have had the same problem when I bought a symbol outside the bot and the bot is not running. Then I use the bot only for sell (set last buy price). Like this will result a lost sell order.

So, I would like to know if **DOTBUSD** bought using the bot or outside (from Binance directly)?

If this is your case, I know the problem and I have a solution for it.

**Comment by uhliksk** [comment] 2022-07-31 18:42
@habibalkhabbaz I'm not doing manual orders. Everything, buy or sell, is made by the bot automatically.

**Comment by uhliksk** [comment] 2022-07-31 18:47
@habibalkhabbaz The NEARBUSD I posted in screenshots section of this issue had also canceled sell orders. I think this bug is related to bot automatically cancelling sell orders when the price is raising.

![image](https://user-images.githubusercontent.com/37454226/182040788-7126c482-1e49-4b09-892f-fb3907b73398.png)

**Comment by uhliksk** [comment] 2022-07-31 19:27
@habibalkhabbaz Is this normal behavior to wait 20 seconds between the sell order is executed and the grid trade is removed?

![image](https://user-images.githubusercontent.com/37454226/182042036-55ee0611-add2-4a81-a698-8ff847019140.png)

**Comment by habibalkhabbaz** [comment] 2022-07-31 19:38
> @habibalkhabbaz Is this normal behavior to wait 20 seconds between the sell order is executed and the grid trade is removed?
> 
> ![image](https://user-images.githubusercontent.com/37454226/182042036-55ee0611-add2-4a81-a698-8ff847019140.png)

Yes, this is the default setting value.

https://github.com/chrisleekr/binance-trading-bot/blob/70b8d0c8c1c81301c2bbd1588770cad78df52e61/config/default.json#L149

You can change it by using your `.env` file. 2 seconds for example:

```
BINANCE_JOBS_TRAILING_TRADE_SYSTEM_TEMPORARY_DISABLE_ACTION_AFTER_CONFIRMING_ORDER=2
```

I am still trying to know what is the actual issue.

**Comment by habibalkhabbaz** [comment] 2022-07-31 19:46
@uhliksk 
Do you mind if you try the same thing on my last PR? I would like to see how it goes.

**Comment by uhliksk** [comment] 2022-07-31 20:13
@habibalkhabbaz I reverted my changes and merged with your PR and also changed `.env` as you suggested. I'll keep full docker logs to better analyze the issue if it happened again.

**Comment by habibalkhabbaz** [comment] 2022-07-31 20:15
@uhliksk 
Thanks! It will be easier to debug.
I am running my bot on that PR too to see how it goes.

**Comment by uhliksk** [comment] 2022-07-31 21:33
@habibalkhabbaz Something wrong has happened since I started the code with your PR merged. Some symbols just stopped updating. When I reverted the code it catched the current values immediatelly.

![image](https://user-images.githubusercontent.com/37454226/182046168-befd0405-1d02-4586-94d7-97778ad950d5.png)

**Comment by uhliksk** [comment] 2022-07-31 21:52
@habibalkhabbaz There is not even "TrailingTrade: Start process..." logged for those symbols. Interesting thing is when I switched back to PR merged code all the same symbol are stuck again. Is it possible it had somehow didn't deleted the flag from cache and keep thinking the task is still executed?

**Comment by uhliksk** [comment] 2022-07-31 22:04
@habibalkhabbaz You should use `await cache.hset(`execute-trailing-trade`, symbol, true);` with TTL value to prevent infinite lock.

**Comment by habibalkhabbaz** [comment] 2022-08-01 04:50
@uhliksk 
Thanks for this good catch. Pushed a fix.
You can delete your Redis cache to work as expected.
It would be better to continue testing on the same PR to see how it goes.

**Comment by uhliksk** [comment] 2022-08-02 18:49
@habibalkhabbaz Since yesterday 53 closed trades without an issue, but there were no multiple cancelled sell orders before the final sell order has been executed. I'll keep logging.

**Comment by habibalkhabbaz** [comment] 2022-08-02 19:31
> @habibalkhabbaz Since yesterday 53 closed trades without an issue, but there were no multiple cancelled sell orders before the final sell order has been executed. I'll keep logging.

Glad to hear that!
Now let's see if the sell order issue already solved or not.

**Comment by uhliksk** [comment] 2022-08-05 20:25
@habibalkhabbaz Sell order issue still exist but I didn't catched the log as I was travelled away and I didn't noticed logging stopped working at morning. But I'm suspicious it somehow triggerred "Remove last buy price" before the sell order is processed. I restarted logging and I hope I'll catch the issue with full log next time.

**Comment by uhliksk** [comment] 2022-08-05 20:33
@habibalkhabbaz
From Binance history I can see the sell order has been set at 13:18:04, then cancelled and new higher sell order has been set at 13:19:30. Then 3 seconds later at 13:19:33 the sell order has been executed and then closed trade has been archived into bot database at 13:19:42.

Second event was very similar. Sell order has been set at 12:44:24, then cancelled and new higher sell order has been set at 13:19:29. Then 9 seconds later at 13:19:38 the sell order has been executed and then closed trade has been archive into bot database at 13:20:36.

**Comment by uhliksk** [comment] 2022-08-05 20:36
@habibalkhabbaz 
![image](https://user-images.githubusercontent.com/37454226/183158814-aed6953e-f648-43ec-b14c-bb408d59783e.png)

**Comment by habibalkhabbaz** [comment] 2022-08-05 22:13
That was sad!

> @habibalkhabbaz From trailing-trade-grid-trade-archive: ![image](https://user-images.githubusercontent.com/37454226/183158814-aed6953e-f648-43ec-b14c-bb408d59783e.png)

It will be helpful for debugging if you can share the whole document to see the buy grids and the sell grids.

**Comment by uhliksk** [comment] 2022-08-06 06:26
@habibalkhabbaz I think it's something wrong with symbol locks or something similar which will cause the planned step is skipped and then never processed again because I also found sometimes sell order is recorded completely in closed trades archive but the grid trade is not reset automatically and symbol si stuck then until I click "Reset Grid Trade" manually. If any operation failed because of lock or some other non-critical issue it should be retried.

![image](https://user-images.githubusercontent.com/37454226/183237016-c39dd8ba-dc34-48ab-8aec-fc68150805c3.png)

**Comment by uhliksk** [comment] 2022-08-06 07:04
@habibalkhabbaz There is no check if transaction has been processed successfully. Result is returned but not processed.

https://github.com/chrisleekr/binance-trading-bot/blob/a9319ad7d65235244571f73efa842ffe1cdae86d/app/cronjob/trailingTradeHelper/configuration.js#L516-L530

https://github.com/chrisleekr/binance-trading-bot/blob/a9319ad7d65235244571f73efa842ffe1cdae86d/app/cronjob/trailingTrade/step/remove-last-buy-price.js#L128-L129

**Comment by uhliksk** [comment] 2022-08-06 07:13
If sell order is executed and not written to db successfully it can cause the issue with sell orders and potentially many other issues. I think I should create new issue for the problem.

**Comment by uhliksk** [comment] 2022-08-06 07:27
@habibalkhabbaz There is not even write concern enabled. I'll create new issue to fix this.

https://github.com/chrisleekr/binance-trading-bot/blob/a9319ad7d65235244571f73efa842ffe1cdae86d/app/helpers/mongo.js#L231-L237

**Comment by uhliksk** [comment] 2022-08-06 10:55
@habibalkhabbaz I found it was introduced by purpose in #288.

**Comment by habibalkhabbaz** [comment] 2022-08-06 11:06
Hello @uhliksk 
Yes, this is intended change to make MongoDB fast.

I think we have to check for the main reason which is why the sell executed order is not saved to DB.

The sell order should be saved directly after placing it and will be archived later if executed. 

https://github.com/chrisleekr/binance-trading-bot/blob/a9319ad7d65235244571f73efa842ffe1cdae86d/app/cronjob/trailingTrade/step/place-sell-order.js#L199

So the question is: is it really not saved and why not?. We have to investigate this.

**Comment by uhliksk** [comment] 2022-08-06 13:02
> So the question is: is it really not saved and why not?. We have to investigate this.

Hello @habibalkhabbaz 

What do you think can cause too big delay between the sell order executed and the last buy price removed? When I posted the smaller part of this log, I didn't noticed there is huge gap for more than 2 minutes. In other cases there is 20 seconds gap based on `BINANCE_JOBS_TRAILING_TRADE_SYSTEM_TEMPORARY_DISABLE_ACTION_AFTER_CONFIRMING_ORDER`.

![image](https://user-images.githubusercontent.com/37454226/183249697-43a8cb5e-4396-46ad-a807-46ce52c02834.png)

**Comment by chrisleekr** [comment] 2022-08-06 13:15
@uhliksk 

> What do you think can cause too big delay between the sell order executed and the last buy price removed? 

That is because the last buy price is not removed immediately after the sell order is executed, which is the intended behaviour. 
It will wait for the next tick and determine whether to remove the last buy price or not.
Before WebSocket implementation, it would be fine because it would run the execution immediately. However, it's relying on the tick now. I assume the gap between sell order and the last buy price is caused by the tick delay.

This issue should be resolved when the queue is implemented.

**Comment by uhliksk** [comment] 2022-08-08 09:19
@habibalkhabbaz Today's event is even stranger as the sell order has been cancelled right before it was processed as executed sell order.

![image](https://user-images.githubusercontent.com/37454226/183382390-839d58b7-9ffb-47ed-b9a2-7fa43f7c8a91.png)

![image](https://user-images.githubusercontent.com/37454226/183382512-52c6291d-3a22-4a88-a9b1-99b1143cc5a9.png)

![image](https://user-images.githubusercontent.com/37454226/183384472-3d1c1ff0-21b5-494f-adc9-afdd05d2bd6f.png)

**Comment by uhliksk** [comment] 2022-08-08 10:05
@habibalkhabbaz It's possible we are hunting MongoDB memory issue here. I'm using Hyper-V with Dynamic Memory enabled for binance-bot VM. I'll try to switch to fixed memory configuration. I've never had an issue with this VM configuration but binance-bot is probably much more resource hungry in ruch hours than any other application I've ever used in my VMs.

https://groups.google.com/g/mongodb-user/c/MapX1Ug_gsI/m/meJvWVAfFQAJ

If that's the issue then still bot should find and process sell order even if it missed it's own event or even when sold manually to keep track of profitability.

**Comment by uhliksk** [comment] 2022-08-08 10:11
@habibalkhabbaz This is `top` from around the time this issue has happened. It doesn't look like a memory issue but I'll still try to switch to fixed memory allocation for this VM.

![image](https://user-images.githubusercontent.com/37454226/183394744-7c66c736-bd0b-4bf0-83f5-a8b7ba9784c0.png)

**Comment by habibalkhabbaz** [comment] 2022-08-08 10:23
Hello @uhliksk 
My suggestion is to put the following line in your `.env` file:

```
BINANCE_LOG_LEVEL=ERROR
```

This will make the `logger` log only errors to console which will lower the memory usage and issues. Try it and let's see if it will solve the current issue or not!

However, what I prefer is to remove all docker containers and restart everything from scratch if you can.
This will make sure you don't have data stuck here and there.

**Comment by uhliksk** [comment] 2022-08-08 10:38
Hello @habibalkhabbaz 

I'm doing `docker system prune` from time to time. I'll try the log level option you suggested. Thank you.

**Comment by chrisleekr** [comment] 2022-08-08 13:00
> @habibalkhabbaz Today's event is even stranger as the sell order has been cancelled internally right before it had to be processed as eell order.

@uhliksk is it possible you can export the logs? So can see what actually happened?

I can see a possible scenario. @habibalkhabbaz correct me if I am wrong.

When the order is executed, from WebSocket, the bot will receive `executionReport` 
- https://github.com/chrisleekr/binance-trading-bot/blob/master/app/binance/user.js#L39

What we need to confirm is, first, was your bot received the WebSocket event? 
Unfortunately, it hasn't been recorded in the database, so we wouldn't know at this point. 
Hence, I have added this PR and will be merged to the master - https://github.com/chrisleekr/binance-trading-bot/pull/460

If it happens again, we should be able to see what happened.

Ah, while I am writing, I found a flow. 

Sorry. I keep mumble-jumble. 

---- 

Let me tidy up.

I opened a new PR - https://github.com/chrisleekr/binance-trading-bot/pull/461
This is to fix Scenario 1. 

Once the order is executed or cancelled whatever happened to the order, it should receive the event via WebSocket.
https://github.com/chrisleekr/binance-trading-bot/blob/master/app/binance/user.js#L39
The order is updated in the database; however, the trailing trade is not executed after the order is updated.

This can cause unexpected behaviour, which I think it shouldn't. But it will make the flow correctly. 

---

The 2nd scenario will need the detailed log from @uhliksk 

@habibalkhabbaz Please verify my scenario.

Normally, this is the flow we would expect how the bot behaves.

```
11:00:26 New sell order is placed
11:00:45 Logged "The order will be cancelled". This log assumed logged from https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/handle-open-orders.js#L178
??:??:?? Received order update event. The last order is updated as cancelled
11:00:47 New sell order is placed
??:??:?? Received order update event. The last order is updated as filled
??:??:?? Process filled order - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/ensure-grid-trade-order-executed.js#L289
```

However, for some reason, the process is messed up. I think the most suspect issue is not executing `trailingTrade` immediately, but there could be another reason.

So what I assume to happen is the below process.

```
11:00:26 New sell order is placed
11:00:45 Logged "The order will be cancelled". This log assumed logged from https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade/step/handle-open-orders.js#L178
11:00:47 New sell order is placed
??:??:?? Received order update event. The last order is updated as filled
??:??:?? Received order update event. The last order is updated as cancelled
11:00:50 Processed cancelled order 
11:01:21 The last buy price is removed
```

I think when we update the last order, we should compare the **timestamp** and **orderId** and make sure we have the last order recording as the last order.
https://github.com/chrisleekr/binance-trading-bot/blob/master/app/binance/user.js#L64

What do you think @habibalkhabbaz?
If you think my theory is valid, then you can update it in my branch - https://github.com/chrisleekr/binance-trading-bot/pull/461

@uhliksk you can try with my branch and see if we can get more logs + the fix is working or not.

**Comment by uhliksk** [comment] 2022-08-08 14:20
@chrisleekr I'm sorry but I don't have full log again. I'm saving log over samba to another machine as the log generated by the bot is massive in my instance and I didn't noticed it filled dedicated partition. Last 50 MB stored locally are just a few last seconds of log which is not helpful.

I think the bot received the sell order cancellation over websocket but as there was no price change, it was not processed by `executeTrailingTrade`˙. Then the bot placed new sell order and sell order was executed on Binance. Sell order execution means the price has changed and this caused `executeTrailingTrade` has been fired and previously received sell order cancellation has been processed. Then finally with sell order cancelled on bot side and balance updated, the last buy price has been removed. If that's how the issue happened then your fix should be working well.

Checking orderId will also be fine to prevent removing wrong order by delayed sell order cancellation report.

I'll try to run with your branch to see it the issue will occur again in next few days. Thank you.

**Comment by chrisleekr** [comment] 2022-08-08 14:27
> I think the bot received the sell order cancellation over websocket but as there was no price change

Yap, that is what I think as well.

> I'll try to run with your branch to see it the issue will occur again in next few days.

Yap, I just tested in my RPi with the test server. It started logging the order update as well.

Btw, when you open the log for the symbol, you can view the data on the right column.
That data is very helpful to debug what is going on.

And when you encounter the same issue, export the log immediately. 
Then we can debug with that log.

**Comment by uhliksk** [comment] 2022-08-08 15:13
> And when you encounter the same issue, export the log immediately. Then we can debug with that log.

Ok, I forgot about that option. Thank you.

**Comment by habibalkhabbaz** [comment] 2022-08-08 17:00
@chrisleekr 
I've finished writing the fix but unfortunately I think I have lack in permission. I can't commit the changes to PR #461.

```
remote: Permission to chrisleekr/binance-trading-bot.git denied to habibalkhabbaz.
```

I can provide the changes as txt if you like since the changes applied only 2 files only: `user.js` and `user.test.js`

**Comment by uhliksk** [comment] 2022-08-08 23:21
@chrisleekr Not a sell order bug yet, but just an interesting "double" execution logged.

![image](https://user-images.githubusercontent.com/37454226/183530723-62185631-a35f-4f80-9a03-c71482ce211b.png)

**Comment by chrisleekr** [comment] 2022-08-09 10:39
@uhliksk That is interesting. So there was New/Filled order update almost the same time and it triggered two executeTrailingTrade. 
Were you able to export the log when it happens? 
If you did, it would be very helpful to debug.

**Comment by chrisleekr** [comment] 2022-08-09 10:46
One thing I just noticed is, that the locking symbol didn't work properly. 

I may have a workaround, but this workaround is very dodge. 
We should implement the queue to fix the fundamental issue.

Let me update workaround first.

**Comment by habibalkhabbaz** [comment] 2022-08-09 11:29
Good catch! @uhliksk @chrisleekr 

However, I think we still need to check for the `orderId` and `transactTime` when we update the order from WebSocket for better stability. What do you think @chrisleekr ? BTW sorry for the interruption xD

Moreover, I was thinking about the queue implementation last few days and I found that the ideal solution is to implement a queue for each symbol so that each symbol will not be waiting for other symbols to complete their job but I think this is not good for the performance.
The other solution is implementing one queue for all symbols but this will make all symbols waiting for their turn in the queue.

Let me know if you have any idea about this @chrisleekr when you have time.

**Comment by chrisleekr** [comment] 2022-08-09 11:41
> I think we still need to check for the orderId and transactTime when we update the order from WebSocket for better stability

I agree. 

The current code - https://github.com/chrisleekr/binance-trading-bot/blob/master/app/cronjob/trailingTrade.js#L39 - only lock the symbol 5 seconds. 
I assume the second order update `SELL - FILLED` came after 5 seconds and execute another trailing trade before finishing the 1st trailing trade execution.
However, I can assume both trailing trade execution got the latest updated order `SELL - FILLED`. 

My plan is to mimic the queue system. If the symbol is locked, I force it to execute the trailing trade 10 seconds later. I will use `setTimeout`.

As mentioned, this is a workaround.  This workaround should be updated when we have a queue.

> to implement a queue for each symbol

Agree. Trailing Trade can be executed simultaneously for other symbols. It should just FIFO execution for the same symbol. 

So for example, if there is an order update event, then put the job into the queue. If there is the following order update event, then it put the job into the queue again. But it does not execute until finishing the running trailing trade job.

**Comment by chrisleekr** [comment] 2022-08-09 13:31
@uhliksk @habibalkhabbaz 

> Not a sell order bug yet, but just an interesting "double" execution logged.

I have updated trailingTrade to be executed 10 secs later when the symbol is locked. With this code, double execution should be fixed.

See the commit: https://github.com/chrisleekr/binance-trading-bot/pull/461/commits/c05c46cab9410006bbada5caab767ca64bd0cc95

I've also updated the log UI to be more descriptive.

![image](https://user-images.githubusercontent.com/5715919/183659472-997afa0f-998a-41f7-bdc8-130ed43a4dd9.png)

- The time now displays milliseconds.
- It will display UUID of the execution to be able to determine the log's process.
- And it also displays the step of the log. 

With this, just a screenshot may help to understand what is going on.
But again, exporting log is much helpful than this.

**Comment by habibalkhabbaz** [comment] 2022-08-09 13:44
Nice update @chrisleekr 

I have a great news also regarding the queue.
I found a way to create multiple queues since they are cheap based on their documentation.
I'll try to implement that and I will open a new PR if everything goes well and after your PR is merged.

**Comment by uhliksk** [comment] 2022-08-09 18:21
@chrisleekr I tried to export log but it crashed my browser as I had 480 minutes limit and it was just too big to process I think. I set back to default 30 minutes and I'll try to catch the problem in real time. I like the changes in log visuals as I prefer to make screenshots which are simple and reliable everytime. I'll merge the commit, thank you.

@habibalkhabbaz I prefer parallel processing of queue because using single queue for all symbols will be pretty narrow bottleneck in rush hours I think.

**Comment by habibalkhabbaz** [comment] 2022-08-09 18:43
>@habibalkhabbaz I prefer parallel processing of queue because using single queue for all symbols will be pretty narrow bottleneck in rush hours I think.

Totally agree @uhliksk 
This is exactly what I am going to try but we will have to wait for #461 to be merged to not have conflicts.

**Comment by chrisleekr** [comment] 2022-08-10 08:11
@habibalkhabbaz

Once @uhliksk say, there is no more issue, then I will merge in.

**Comment by chrisleekr** [comment] 2022-08-10 12:08
@uhliksk Answered on the PR. So did you encounter any issue so far?

**Comment by uhliksk** [comment] 2022-08-10 12:42
Accidentally I ran a massive test for sell orders recently. :)

I had to do some maintenance on my VM when this happened on almost every pair.

![image](https://user-images.githubusercontent.com/37454226/183903306-a2466fc2-11c9-4fa9-9e06-f662faeb0b1a.png)

I started VM immediatelly which caused a massive sell-out.

![image](https://user-images.githubusercontent.com/37454226/183903607-e1db3066-eba1-4ac3-a5fa-45a8249807c4.png)

There were 19 sell orders placed and executed in just a few seconds and I can confirm all of them were processed without an issue.

**Comment by chrisleekr** [comment] 2022-08-10 12:44
Oh, nice. Very good.

Ok, I will merge in.

**Comment by uhliksk** [comment] 2022-08-10 12:49
@chrisleekr Again another batch of 14 sell orders has been closed. I'll check logs for all the sell orders executed recently to see if there are any potential anomalies recorded. I saved whole `trailing-trade-logs` in case there will be something interesting.

**Comment by uhliksk** [comment] 2022-08-10 12:54
Strange thing. There are no new buy orders placed since this 'nuclear meltdown' happend. In docker log there is a bunch of lines like this:

`{"name":"binance-api","version":"0.0.88","hostname":"73b0809731b1","pid":45,"gitHash":"unspecified","server":"binance","jobName":"trailingTrade","correlationId":"42fa3feb-f644-4979-8b6d-8e44491792dd","level":50,"err":{"message":"Stop price would trigger immediately.","name":"Error","stack":"Error: Stop price would trigger immediately.\n    at /srv/node_modules/binance-api-node/dist/http-client.js:100:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async execute (/srv/dist/server.js:1:38463)\n    at async /srv/dist/server.js:1:8847\n    at async errorHandlerWrapper (/srv/dist/server.js:1:87322)\n    at async P (/srv/dist/server.js:1:7295)","code":-2010},"errorCode":-2010,"debug":true,"msg":"⚠ Execution failed.","time":"2022-08-10T12:51:41.677Z","v":0}
`

**Comment by uhliksk** [comment] 2022-08-10 12:57
@chrisleekr I can create another issue as I think this is something not related to problem discussed in this issue.

**Comment by chrisleekr** [comment] 2022-08-10 12:58
@uhliksk 
Btw, that is a valid error from Binance.

**Closed** 2022-08-10 12:59 UTC
Labels: bug

**Comment by eppenga** [comment] 2022-09-26 09:45
I can confirm that I have the same issue. Also sometimes my stop loss sell orders double up.

Here are some logs:
{
  "_id": "63316872d7c6a3394960f1f9",
  "symbol": "SOLBUSD",
  "msg": "The grid trade #1 sell order will be placed.",
  "loggedAt": "2022-09-26T08:53:06.805Z",
  "data": {
    "helper": "queue",
    "jobName": "trailingTrade",
    "correlationId": "cddabf88-4971-4d91-af97-058a2a6ab24a",
    "stepName": "place-sell-order",
    "function": "order",
    "orderParams": {
      "symbol": "SOLBUSD",
      "side": "sell",
      "type": "STOP_LOSS_LIMIT",
      "quantity": 3.29,
      "stopPrice": 33.07,
      "price": 33.04,
      "timeInForce": "GTC"
    }
  }
}

And then suddenly the quantity doubles:
{
  "_id": "63316a06d7c6a3394960f23a",
  "symbol": "SOLBUSD",
  "msg": "The grid trade #1 sell order will be placed.",
  "loggedAt": "2022-09-26T08:59:50.619Z",
  "data": {
    "helper": "queue",
    "jobName": "trailingTrade",
    "correlationId": "95a34487-d0fe-4798-bbb6-a24178b6608f",
    "stepName": "place-sell-order",
    "function": "order",
    "orderParams": {
      "symbol": "SOLBUSD",
      "side": "sell",
      "type": "STOP_LOSS_LIMIT",
      "quantity": 6.58,
      "stopPrice": 33.13,
      "price": 33.1,
      "timeInForce": "GTC"
    }
  }
}

As you can see it jumps from 3.29 to 6.58 faling to sell.
