### ISSUE TITLE
open orders count

### ISSUE THREAD

**Issue by eth-man** [chrisleekr/binance-trading-bot#332] opened 2021-09-25 15:51 UTC
## Version
Running Version: v0.0.79 (244734f)
## Description
not sure if this a bug
if bot set 5 open orders how its possible my bot executing up to 7 open orders ?
if i want to use 5 open orders do i need to change 3 open orders and 2 buy orders for example ?

![image](https://user-images.githubusercontent.com/8633885/134777606-c7dadf7a-9c55-4807-84aa-45b8a5dbfa2f.png)
![image](https://user-images.githubusercontent.com/8633885/134777619-f79157d3-8488-4f46-a8bc-488f024f3edc.png)

**Comment by chrisleekr** [comment] 2021-09-26 03:55
I don't understand your question.

`Open trades 5` mean, you have 5 symbols recorded with the last buy price.
`Open orders - buy 2` mean, you have 2 symbols with open orders for buying.

What is the issue?

**Comment by eth-man** [comment] 2021-09-26 05:15
Yesterday after taking the screenshot the bot reached 6 open trades which make him not opening more grid trades due to max open trades
Then I increased open trades to 6 and now settings of 6 open trades and 3 buy trades the bot  currently having 9 open trades

**Comment by chrisleekr** [comment] 2021-09-26 05:44
Look, I don't have access to your bot. Therefore, I won't be able to tell what the issue is without any logs, screenshots.
Please provide the screenshots and logs.

**Comment by chrisleekr** [comment] 2021-09-29 09:29
I didn't hear from you for a while. I will close the issue. If you find any issue, please open new issue.

**Closed by chrisleekr** 2021-09-29 09:29 UTC
Labels: question
