### ISSUE TITLE
Bot flooding by error ETIMEDOUT.

### ISSUE THREAD

**Issue by pedrohusky** [chrisleekr/binance-trading-bot#188] opened 2021-05-18 22:57 UTC
Hi. I have setup everything correctly I guess, because it is working and I'm getting money.

The problems: 

## Multiple buy orders sent in slack

1 - idk why but sometimes when the bot go buy a coin it stays checking the open order every second and this is flooding my slack, and I guess it shouldn't happen. But after 1 minute it stops.

See screenshot: ![Screenshot_20210518-194859.png](https://user-images.githubusercontent.com/59580251/118733341-78c48800-b812-11eb-9513-a95a04fc8bb2.png)

## Execution Failed - ETIMEDOUT

2 - My bot works flawlessly (ignoring the bug above) for at +-6hrs. Then it will REALLY spam my slack channel with these errors:

![Screenshot_20210518-125157.png](https://user-images.githubusercontent.com/59580251/118733568-e2dd2d00-b812-11eb-9ea2-61c8d33b23be.png)
![Screenshot_20210518-125201.png](https://user-images.githubusercontent.com/59580251/118733581-e8d30e00-b812-11eb-8f7b-80393b43a64f.png)

Don't know why it happens every 6 hours. But the solution I've found is: 

1 -- Shut down the bot by clicking the stop button on Docker Desktop (I'm in windows 10)

2 --  then open a powershell and send a wsl --shutdown 

3 -- restart wsl with windows notification

4 -- start bot by clicking start button on Docker Desktop

5 -- it will work flawlessly for 6 more hours.

Help needed.

My bot version: ![Screenshot_20210518-195930.png](https://user-images.githubusercontent.com/59580251/118734008-d86f6300-b813-11eb-8bd8-02f4a713a180.png)

I'm currently at the feature-monitoring-simultaneously branch.

**Comment by pedrohusky** [comment] 2021-05-19 00:29
Hi, another thing: that message is wrong, no?

![Screenshot_20210518-212354.png](https://user-images.githubusercontent.com/59580251/118739485-fba00f80-b81f-11eb-81aa-456ecb704700.png)

It's supposed to say sell, not buy. Idk how to open another bug through phone

**Comment by chrisleekr** [comment] 2021-05-21 01:17
@pedrohusky 

`1 - idk why but sometimes when the bot go buy a coin it stays checking the open order every second and this is flooding my slack, and I guess it shouldn't happen. But after 1 minute it stops.`

That is not a bug, that is the bot checking the order. When Binance API is not returning the placed order in the open order call, the bot will try to confirm the order exists in the open order.

You can disable order confirming the slack message by setting this environment parameter - https://github.com/chrisleekr/binance-trading-bot/blob/feature-monitoring-simultaneously/config/custom-environment-variables.json#L48

Then it will not send an order confirming message to Slack.

`2 - My bot works flawlessly (ignoring the bug above) for at +-6hrs. Then it will REALLY spam my slack channel with these errors:`

Again, not a bug. As you can see ETIMEDOUT in the error message, it means your bot was not able to receive the response from Binance API. Typically due to connection error. 

I also not sure why it is happening every 6 hours, but you can restart the bot every hour something like that.
Refer https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#setup-cronjob-to-restart-the-bot-periodically

`It's supposed to say sell, not buy. Idk how to open another bug through phone`

Again, not a bug. The message is correct. If the balance is not enough to sell, it removes `last buy price`.

**Comment by pedrohusky** [comment] 2021-05-21 01:28
@chrisleekr Oh, really sorry about the second comment. I really didn't read it right. Forget it. Sorry.

I will see what I'll do about the order messages. But if you said that is a feature, let's keep that way. I like to know when the bot bought. :)

About my problem of ETIMEDOUT, I really don't know why this is happening. Maybe a cache bug? Because it just needs a restart.

**Comment by chrisleekr** [comment] 2021-05-21 01:32
@pedrohusky 

> I will see what I'll do about the order messages. But if you said that is a feature, let's keep that way. I like to know when the bot bought. :)

Again, you can always turn it off by setting the environment configuration if you want. 

> About my problem of ETIMEDOUT, I really don't know why this is happening. Maybe a cache bug? Because it just needs a restart.

That is nothing to do with the bot. It's your server or network issue.

**Comment by pedrohusky** [comment] 2021-05-21 02:04
> @pedrohusky 
> 
> > I will see what I'll do about the order messages. But if you said that is a feature, let's keep that way. I like to know when the bot bought. :)
> 
> Again, you can always turn it off by setting the environment configuration if you want. 

Sure. :)

> 
> > About my problem of ETIMEDOUT, I really don't know why this is happening. Maybe a cache bug? Because it just needs a restart.
> 
> That is nothing to do with the bot. It's your server or network issue. 
> 

What can I do? Have gone through your troubleshoot, sync the clock, downloaded everything again, and still the same error. I could setup a reboot script, will go after that link you mentioned. Thanks for your attention :D

**Comment by chrisleekr** [comment] 2021-05-21 02:37
@pedrohusky 

Hmm, I really don't know how I set cronjob in Windows WSL to restart docker.

https://blog.snowme34.com/post/schedule-tasks-using-crontab-on-windows-10-with-wsl/index.html#Create-crontab-Job

Just did a quick search in Google, seems you can?
Google will be your good teacher.

**Comment by chrisleekr** [comment] 2021-05-22 06:47
@pedrohusky 

Please close the issue if your issue is resolved.

**Closed** 2021-05-22 11:30 UTC
Labels: question
